package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"golem-engine/schema"
)

var protoCSDefault = map[string]string{
	"double": "0",
	"float":  "0f",
	"int32":  "0",
	"int64":  "0",
	"uint32": "0",
	"uint64": "0",
	"sint32": "0",
	"sint64": "0",
	"bool":   "false",
	"string": `""`,
	"bytes":  "System.Array.Empty<byte>()",
}

var protoCSZero = map[string]string{
	"double": "0",
	"float":  "0f",
	"int32":  "0",
	"int64":  "0",
	"uint32": "0",
	"uint64": "0",
	"sint32": "0",
	"sint64": "0",
	"bool":   "false",
	"string": `""`,
	"bytes":  "",
}

var protoCSReaderMethod = map[string]string{
	"double": "Double",
	"float":  "Float",
	"int32":  "Int32",
	"int64":  "Int64",
	"uint32": "Uint32",
	"uint64": "Uint64",
	"sint32": "Sint32",
	"sint64": "Sint64",
	"bool":   "Bool",
	"string": "String",
	"bytes":  "Bytes",
}

var protoCSWriterMethod = map[string]string{
	"double": "Double",
	"float":  "Float",
	"int32":  "Int32",
	"int64":  "Int64",
	"uint32": "Uint32",
	"uint64": "Uint64",
	"sint32": "Sint32",
	"sint64": "Sint64",
	"bool":   "Bool",
	"string": "String",
	"bytes":  "Bytes",
}

func generateCSharpProto(
	outDir string,
	golemImport string,
	goPackage string,
	entities []schema.EntityData,
	commands []schema.CommandData,
	worldTypes []schema.WorldTypeData,
	events []schema.EventData,
	proto schema.ProtoTemplateData,
) error {
	namespace := csharpNamespace(goPackage)
	if err := generateCSharpEntitiesProto(outDir, golemImport, namespace, entities, commands, proto); err != nil {
		return err
	}
	if len(worldTypes) > 0 {
		if err := generateCSharpWorldProto(outDir, golemImport, namespace, proto); err != nil {
			return err
		}
	}
	if len(events) > 0 {
		if err := generateCSharpEventProto(outDir, golemImport, namespace, proto); err != nil {
			return err
		}
	}
	return nil
}

func generateCSharpEntitiesProto(outDir, golemImport, namespace string, entities []schema.EntityData, commands []schema.CommandData, proto schema.ProtoTemplateData) error {
	var b strings.Builder
	writeCSharpHeader(&b, golemImport, namespace)

	for _, ct := range proto.CustomTypes {
		writeCSCustomType(&b, ct)
	}
	for _, ent := range entities {
		writeCSMessageClass(&b, ent.Name+"State", entityStateCSFields(ent))
		writeCSMessageClass(&b, ent.Name+"Delta", entityDeltaCSFields(ent))
	}
	writeCSMessageClass(&b, "EntityRemoved", []msgField{
		{Name: "EntityId", ProtoType: "int64", Tag: 1},
		{Name: "Revision", ProtoType: "uint64", Tag: entityRevisionProtoTag},
	})
	writeCSEntityUpdateClass(&b, proto)
	for _, cmd := range commands {
		writeCSCommandClass(&b, cmd)
	}
	if len(commands) > 0 {
		writeCSClientMessageClass(&b, proto)
		writeCSClientPacketClass(&b)
	}
	writeCSharpFooter(&b, namespace)

	outPath := filepath.Join(outDir, "EntitiesPb.cs")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  wrote %s\n", outPath)
	return nil
}

func writeCSharpHeader(b *strings.Builder, golemImport, namespace string) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("// GENERATED by Golem Engine - do not edit.")
	w("using System;")
	w("using System.Collections.Generic;")
	w("using %s;", golemImport)
	w("")
	w("namespace %s", namespace)
	w("{")
}

func writeCSharpFooter(b *strings.Builder, namespace string) {
	fmt.Fprintln(b, "}")
}

func entityStateCSFields(ent schema.EntityData) []msgField {
	fields := []msgField{
		{Name: "EntityId", ProtoType: "int64", Tag: 1},
		{Name: "PosX", ProtoType: "float", Tag: 2},
		{Name: "PosY", ProtoType: "float", Tag: 3},
	}
	if ent.Is3D {
		fields = append(fields, msgField{Name: "PosZ", ProtoType: "float", Tag: 4})
	}
	fields = append(fields, msgField{Name: "Revision", ProtoType: "uint64", Tag: entityRevisionProtoTag})
	for _, v := range ent.AllVars {
		fields = append(fields, varInfoToEntityCSMsgField(ent, v, false))
	}
	return fields
}

func entityDeltaCSFields(ent schema.EntityData) []msgField {
	fields := []msgField{
		{Name: "EntityId", ProtoType: "int64", Tag: 1},
		{Name: "PosX", ProtoType: "float", Tag: 2, IsOptional: true},
		{Name: "PosY", ProtoType: "float", Tag: 3, IsOptional: true},
	}
	if ent.Is3D {
		fields = append(fields, msgField{Name: "PosZ", ProtoType: "float", Tag: 4, IsOptional: true})
	}
	fields = append(fields, msgField{Name: "Revision", ProtoType: "uint64", Tag: entityRevisionProtoTag})
	for _, v := range ent.TickVars {
		fields = append(fields, varInfoToEntityCSMsgField(ent, v, true))
	}
	return fields
}

func varInfoToCSMsgField(v schema.VarInfo, isDelta bool) msgField {
	return msgField{
		Name:            v.CSProtoField,
		ProtoType:       v.ProtoType,
		Tag:             v.ProtoTag,
		IsRepeated:      v.IsRepeated,
		IsMap:           v.IsMap,
		MapKeyProtoType: v.MapKeyProtoType,
		ElemProtoType:   v.ElemProtoType,
		ElemIsCustom:    v.ElemIsCustom,
		ElemTSType:      v.ElemCSType,
		MapKeyTSType:    v.MapKeyCSType,
		IsOptional:      isDelta,
	}
}

func varInfoToEntityCSMsgField(ent schema.EntityData, v schema.VarInfo, isDelta bool) msgField {
	mf := varInfoToCSMsgField(v, isDelta)
	mf.Tag = entityProtoTag(ent, v.UserTag)
	return mf
}

func csType(protoType string) string {
	switch protoType {
	case "double":
		return "double"
	case "float":
		return "float"
	case "int32", "sint32":
		return "int"
	case "int64", "sint64":
		return "long"
	case "uint32":
		return "uint"
	case "uint64":
		return "ulong"
	case "bool":
		return "bool"
	case "string":
		return "string"
	case "bytes":
		return "byte[]"
	default:
		return protoType
	}
}

func nullableCSType(protoType string) string {
	if protoType == "bytes" || protoType == "string" {
		return csType(protoType)
	}
	return csType(protoType) + "?"
}

func writeCSMessageClass(b *strings.Builder, name string, fields []msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("    public sealed class %s", name)
	w("    {")
	for i, f := range fields {
		isEntityID := i == 0 && f.Name == "EntityId"
		switch {
		case f.IsRepeated:
			t := fmt.Sprintf("List<%s>", f.ElemTSType)
			if f.IsOptional {
				w("        public %s %s { get; set; }", t, f.Name)
			} else {
				w("        public %s %s { get; set; } = new %s();", t, f.Name, t)
			}
		case f.IsMap:
			t := fmt.Sprintf("Dictionary<%s, %s>", f.MapKeyTSType, f.ElemTSType)
			if f.IsOptional {
				w("        public %s %s { get; set; }", t, f.Name)
			} else {
				w("        public %s %s { get; set; } = new %s();", t, f.Name, t)
			}
		case f.IsOptional && !isEntityID:
			w("        public %s %s { get; set; }", nullableCSType(f.ProtoType), f.Name)
		default:
			w("        public %s %s { get; set; } = %s;", csType(f.ProtoType), f.Name, protoCSDefault[f.ProtoType])
		}
	}
	w("")
	writeCSMessageEncode(b, name, fields)
	w("")
	writeCSMessageDecode(b, name, fields)
	w("    }")
	w("")
}

func writeCSMessageEncode(b *strings.Builder, name string, fields []msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("        public static byte[] Encode(%s m)", name)
	w("        {")
	w("            var w = new PbWriter();")
	for i, f := range fields {
		isEntityID := i == 0 && f.Name == "EntityId"
		switch {
		case f.IsRepeated:
			writeCSCollectionEncode(b, f)
		case f.IsMap:
			writeCSMapEncode(b, f)
		case f.IsOptional && !isEntityID:
			wt := protoWireType[f.ProtoType]
			wm := protoCSWriterMethod[f.ProtoType]
			if f.ProtoType == "string" || f.ProtoType == "bytes" {
				w("            if (m.%s != null) w.Tag(%d, %d).%s(m.%s);", f.Name, f.Tag, wt, wm, f.Name)
			} else {
				w("            if (m.%s.HasValue) w.Tag(%d, %d).%s(m.%s.Value);", f.Name, f.Tag, wt, wm, f.Name)
			}
		case f.ProtoType == "bytes":
			w("            if (m.%s.Length > 0) w.Tag(%d, 2).Bytes(m.%s);", f.Name, f.Tag, f.Name)
		default:
			wt := protoWireType[f.ProtoType]
			wm := protoCSWriterMethod[f.ProtoType]
			w("            if (m.%s != %s) w.Tag(%d, %d).%s(m.%s);", f.Name, protoCSZero[f.ProtoType], f.Tag, wt, wm, f.Name)
		}
	}
	w("            return w.Finish();")
	w("        }")
}

func writeCSMessageDecode(b *strings.Builder, name string, fields []msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("        public static %s Decode(byte[] bytes)", name)
	w("        {")
	w("            var r = new PbReader(bytes);")
	w("            var m = new %s();", name)
	w("            while (!r.Done)")
	w("            {")
	w("                var tag = r.Tag();")
	w("                switch (tag.Field)")
	w("                {")
	for _, f := range fields {
		switch {
		case f.IsRepeated:
			writeCSCollectionDecode(b, f)
		case f.IsMap:
			writeCSMapDecode(b, f)
		default:
			rm := protoCSReaderMethod[f.ProtoType]
			w("                    case %d: m.%s = r.%s(); break;", f.Tag, f.Name, rm)
		}
	}
	w("                    default: r.Skip(tag.Wire); break;")
	w("                }")
	w("            }")
	w("            return m;")
	w("        }")
}

func writeCSCustomType(b *strings.Builder, ct schema.CustomTypeData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("    public sealed class %s", ct.Name)
	w("    {")
	for _, f := range ct.Fields {
		w("        public %s %s { get; set; } = %s;", csType(f.ProtoType), schema.SnakeToPascal(f.SnakeName), protoCSDefault[f.ProtoType])
	}
	w("")
	w("        public static byte[] Encode(%s m)", ct.Name)
	w("        {")
	w("            var w = new PbWriter();")
	for _, f := range ct.Fields {
		name := schema.SnakeToPascal(f.SnakeName)
		wt := protoWireType[f.ProtoType]
		wm := protoCSWriterMethod[f.ProtoType]
		if f.ProtoType == "bytes" {
			w("            if (m.%s.Length > 0) w.Tag(%d, %d).%s(m.%s);", name, f.ProtoTag, wt, wm, name)
		} else {
			w("            if (m.%s != %s) w.Tag(%d, %d).%s(m.%s);", name, protoCSZero[f.ProtoType], f.ProtoTag, wt, wm, name)
		}
	}
	w("            return w.Finish();")
	w("        }")
	w("")
	w("        public static %s Decode(byte[] bytes)", ct.Name)
	w("        {")
	w("            var r = new PbReader(bytes);")
	w("            var m = new %s();", ct.Name)
	w("            while (!r.Done)")
	w("            {")
	w("                var tag = r.Tag();")
	w("                switch (tag.Field)")
	w("                {")
	for _, f := range ct.Fields {
		w("                    case %d: m.%s = r.%s(); break;", f.ProtoTag, schema.SnakeToPascal(f.SnakeName), protoCSReaderMethod[f.ProtoType])
	}
	w("                    default: r.Skip(tag.Wire); break;")
	w("                }")
	w("            }")
	w("            return m;")
	w("        }")
	w("    }")
	w("")
}

func writeCSCollectionEncode(b *strings.Builder, f msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	if f.IsOptional {
		w("            if (m.%s != null)", f.Name)
		w("            {")
		w("                if (m.%s.Count == 0) w.Tag(%d, 2).Bytes(Array.Empty<byte>());", f.Name, f.Tag)
		w("                else foreach (var item in m.%s)", f.Name)
		w("                {")
		writeCSCollectionElemEncode(b, f, "                    ")
		w("                }")
		w("            }")
		return
	}
	w("            foreach (var item in m.%s)", f.Name)
	w("            {")
	writeCSCollectionElemEncode(b, f, "                ")
	w("            }")
}

func writeCSCollectionElemEncode(b *strings.Builder, f msgField, indent string) {
	if f.ElemIsCustom {
		fmt.Fprintf(b, "%sw.Tag(%d, 2).Bytes(%s.Encode(item));\n", indent, f.Tag, f.ElemProtoType)
		return
	}
	wt := protoWireType[f.ElemProtoType]
	wm := protoCSWriterMethod[f.ElemProtoType]
	if wt == 2 {
		fmt.Fprintf(b, "%sw.Tag(%d, 2).%s(item);\n", indent, f.Tag, wm)
	} else {
		fmt.Fprintf(b, "%s{ var inner = new PbWriter(); inner.%s(item); w.Tag(%d, 2).Bytes(inner.Finish()); }\n", indent, wm, f.Tag)
	}
}

func writeCSCollectionDecode(b *strings.Builder, f msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("                    case %d:", f.Tag)
	w("                    {")
	if f.IsOptional {
		w("                        m.%s ??= new List<%s>();", f.Name, f.ElemTSType)
	}
	w("                        var payload = r.Bytes();")
	w("                        if (payload.Length > 0)")
	w("                        {")
	if f.ElemIsCustom {
		w("                            m.%s.Add(%s.Decode(payload));", f.Name, f.ElemProtoType)
	} else {
		w("                            var inner = new PbReader(payload);")
		w("                            m.%s.Add(inner.%s());", f.Name, protoCSReaderMethod[f.ElemProtoType])
	}
	w("                        }")
	w("                        break;")
	w("                    }")
}

func writeCSMapEncode(b *strings.Builder, f msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	if f.IsOptional {
		w("            if (m.%s != null)", f.Name)
		w("            {")
		w("                if (m.%s.Count == 0) w.Tag(%d, 2).Bytes(Array.Empty<byte>());", f.Name, f.Tag)
		w("                else foreach (var pair in m.%s)", f.Name)
		w("                {")
		writeCSMapEntryEncode(b, f, "                    ")
		w("                }")
		w("            }")
		return
	}
	w("            foreach (var pair in m.%s)", f.Name)
	w("            {")
	writeCSMapEntryEncode(b, f, "                ")
	w("            }")
}

func writeCSMapEntryEncode(b *strings.Builder, f msgField, indent string) {
	fmt.Fprintf(b, "%svar kv = new PbWriter();\n", indent)
	fmt.Fprintf(b, "%skv.Tag(1, %d).%s(pair.Key);\n", indent, protoWireType[f.MapKeyProtoType], protoCSWriterMethod[f.MapKeyProtoType])
	if f.ElemIsCustom {
		fmt.Fprintf(b, "%skv.Tag(2, 2).Bytes(%s.Encode(pair.Value));\n", indent, f.ElemProtoType)
	} else {
		fmt.Fprintf(b, "%skv.Tag(2, %d).%s(pair.Value);\n", indent, protoWireType[f.ElemProtoType], protoCSWriterMethod[f.ElemProtoType])
	}
	fmt.Fprintf(b, "%sw.Tag(%d, 2).Bytes(kv.Finish());\n", indent, f.Tag)
}

func writeCSMapDecode(b *strings.Builder, f msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("                    case %d:", f.Tag)
	w("                    {")
	w("                        var payload = r.Bytes();")
	w("                        if (payload.Length > 0)")
	w("                        {")
	w("                            var itemReader = new PbReader(payload);")
	w("                            var key = %s;", protoCSDefault[f.MapKeyProtoType])
	w("                            var value = %s;", csCollectionValDefault(f))
	w("                            while (!itemReader.Done)")
	w("                            {")
	w("                                var itemTag = itemReader.Tag();")
	w("                                switch (itemTag.Field)")
	w("                                {")
	w("                                    case 1: key = itemReader.%s(); break;", protoCSReaderMethod[f.MapKeyProtoType])
	if f.ElemIsCustom {
		w("                                    case 2: value = %s.Decode(itemReader.Bytes()); break;", f.ElemProtoType)
	} else {
		w("                                    case 2: value = itemReader.%s(); break;", protoCSReaderMethod[f.ElemProtoType])
	}
	w("                                    default: itemReader.Skip(itemTag.Wire); break;")
	w("                                }")
	w("                            }")
	if f.IsOptional {
		w("                            m.%s ??= new Dictionary<%s, %s>();", f.Name, f.MapKeyTSType, f.ElemTSType)
	}
	w("                            m.%s[key] = value;", f.Name)
	w("                        }")
	w("                        else")
	w("                        {")
	if f.IsOptional {
		w("                            m.%s ??= new Dictionary<%s, %s>();", f.Name, f.MapKeyTSType, f.ElemTSType)
	}
	w("                        }")
	w("                        break;")
	w("                    }")
}

func csCollectionValDefault(f msgField) string {
	if f.ElemIsCustom {
		return "new " + f.ElemProtoType + "()"
	}
	return protoCSDefault[f.ElemProtoType]
}

func writeCSEntityUpdateClass(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("    public sealed class EntityUpdate")
	w("    {")
	for _, uf := range proto.EntityUpdateFields {
		w("        public %s %s { get; set; }", uf.MessageType, schema.SnakeToPascal(uf.SnakeName))
	}
	w("        public EntityRemoved EntityRemoved { get; set; }")
	w("")
	w("        public static EntityUpdate Decode(byte[] bytes)")
	w("        {")
	w("            var r = new PbReader(bytes);")
	w("            var m = new EntityUpdate();")
	w("            while (!r.Done)")
	w("            {")
	w("                var tag = r.Tag();")
	w("                switch (tag.Field)")
	w("                {")
	for _, uf := range proto.EntityUpdateFields {
		w("                    case %d: m.%s = %s.Decode(r.Bytes()); break;", uf.Tag, schema.SnakeToPascal(uf.SnakeName), uf.MessageType)
	}
	w("                    case %d: m.EntityRemoved = EntityRemoved.Decode(r.Bytes()); break;", proto.EntityRemovedTag)
	w("                    default: r.Skip(tag.Wire); break;")
	w("                }")
	w("            }")
	w("            return m;")
	w("        }")
	w("    }")
	w("")
}

func writeCSCommandClass(b *strings.Builder, cmd schema.CommandData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("    public sealed class %sCommand", cmd.Name)
	w("    {")
	if cmd.Target == "entity" {
		w("        public long EntityId { get; set; }")
	}
	for _, f := range cmd.Fields {
		w("        public %s %s { get; set; } = %s;", f.CSType, schema.SnakeToPascal(f.SnakeName), f.CSDefault)
	}
	w("")
	w("        public static byte[] Encode(%sCommand m)", cmd.Name)
	w("        {")
	w("            var w = new PbWriter();")
	if cmd.Target == "entity" {
		w("            if (m.EntityId != 0) w.Tag(1, 0).Int64(m.EntityId);")
	}
	for _, f := range cmd.Fields {
		name := schema.SnakeToPascal(f.SnakeName)
		if f.IsCustom {
			w("            { var bytes = %s.Encode(m.%s); if (bytes.Length > 0) w.Tag(%d, 2).Bytes(bytes); }", f.ProtoType, name, f.ProtoTag)
			continue
		}
		wt := protoWireType[f.ProtoType]
		wm := protoCSWriterMethod[f.ProtoType]
		if f.ProtoType == "bytes" {
			w("            if (m.%s.Length > 0) w.Tag(%d, %d).%s(m.%s);", name, f.ProtoTag, wt, wm, name)
		} else {
			w("            if (m.%s != %s) w.Tag(%d, %d).%s(m.%s);", name, protoCSZero[f.ProtoType], f.ProtoTag, wt, wm, name)
		}
	}
	w("            return w.Finish();")
	w("        }")
	w("    }")
	w("")
}

func writeCSClientMessageClass(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("    public sealed class ClientMessage")
	w("    {")
	for _, cmf := range proto.ClientMessageFields {
		w("        public %s %s { get; set; }", cmf.MessageType, schema.SnakeToPascal(cmf.SnakeName))
	}
	w("")
	w("        public static byte[] Encode(ClientMessage m)")
	w("        {")
	w("            var w = new PbWriter();")
	for _, cmf := range proto.ClientMessageFields {
		fieldName := schema.SnakeToPascal(cmf.SnakeName)
		w("            if (m.%s != null) w.Tag(%d, 2).Bytes(%s.Encode(m.%s));", fieldName, cmf.Tag, cmf.MessageType, fieldName)
	}
	w("            return w.Finish();")
	w("        }")
	w("    }")
	w("")
}

func writeCSClientPacketClass(b *strings.Builder) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("    public static class ClientPacket")
	w("    {")
	w("        public static byte[] Encode(IReadOnlyList<byte[]> frames)")
	w("        {")
	w("            var w = new PbWriter();")
	w("            foreach (var frame in frames) w.Tag(1, 2).Bytes(frame);")
	w("            return w.Finish();")
	w("        }")
	w("    }")
	w("")
}

func generateCSharpWorldProto(outDir, golemImport, namespace string, proto schema.ProtoTemplateData) error {
	var b strings.Builder
	writeCSharpHeader(&b, golemImport, namespace)
	for _, wt := range proto.WorldTypes {
		writeCSMessageClass(&b, wt.DataName, worldDataCSFields(wt))
	}
	writeCSWorldUpdateClass(&b, proto)
	writeCSharpFooter(&b, namespace)
	outPath := filepath.Join(outDir, "WorldPb.cs")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  wrote %s\n", outPath)
	return nil
}

func worldDataCSFields(wt schema.WorldTypeData) []msgField {
	var fields []msgField
	for _, f := range wt.Fields {
		fields = append(fields, worldFieldToCSMsgField(f))
	}
	return fields
}

func worldFieldToCSMsgField(f schema.WorldFieldInfo) msgField {
	return msgField{
		Name:            f.CSProtoField,
		ProtoType:       f.ProtoType,
		Tag:             f.ProtoTag,
		IsRepeated:      f.IsRepeated,
		IsMap:           f.IsMap,
		MapKeyProtoType: f.MapKeyProtoType,
		ElemProtoType:   f.ElemProtoType,
		ElemIsCustom:    f.ElemIsCustom,
		ElemTSType:      f.ElemCSType,
		MapKeyTSType:    f.MapKeyCSType,
	}
}

func writeCSWorldUpdateClass(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("    public sealed class WorldUpdate")
	w("    {")
	for _, wuf := range proto.WorldUpdateFields {
		w("        public %s %s { get; set; }", wuf.MessageType, schema.SnakeToPascal(wuf.SnakeName))
	}
	w("")
	w("        public static WorldUpdate Decode(byte[] bytes)")
	w("        {")
	w("            var r = new PbReader(bytes);")
	w("            var m = new WorldUpdate();")
	w("            while (!r.Done)")
	w("            {")
	w("                var tag = r.Tag();")
	w("                switch (tag.Field)")
	w("                {")
	for _, wuf := range proto.WorldUpdateFields {
		w("                    case %d: m.%s = %s.Decode(r.Bytes()); break;", wuf.Tag, schema.SnakeToPascal(wuf.SnakeName), wuf.MessageType)
	}
	w("                    default: r.Skip(tag.Wire); break;")
	w("                }")
	w("            }")
	w("            return m;")
	w("        }")
	w("    }")
	w("")
}

func generateCSharpEventProto(outDir, golemImport, namespace string, proto schema.ProtoTemplateData) error {
	var b strings.Builder
	writeCSharpHeader(&b, golemImport, namespace)
	for _, ev := range proto.Events {
		writeCSEventClass(&b, ev)
	}
	writeCSServerEventClass(&b, proto)
	writeCSharpFooter(&b, namespace)
	outPath := filepath.Join(outDir, "EventsPb.cs")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  wrote %s\n", outPath)
	return nil
}

func writeCSEventClass(b *strings.Builder, ev schema.EventData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("    public sealed class %sEvent", ev.Name)
	w("    {")
	if ev.EntityType != "" {
		w("        public long EntityId { get; set; }")
	}
	for _, f := range ev.Fields {
		w("        public %s %s { get; set; } = %s;", f.CSType, schema.SnakeToPascal(f.SnakeName), f.CSDefault)
	}
	w("")
	w("        public static byte[] Encode(%sEvent m)", ev.Name)
	w("        {")
	w("            var w = new PbWriter();")
	if ev.EntityType != "" {
		w("            if (m.EntityId != 0) w.Tag(1, 0).Int64(m.EntityId);")
	}
	for _, f := range ev.Fields {
		name := schema.SnakeToPascal(f.SnakeName)
		if f.IsCustom {
			w("            { var bytes = %s.Encode(m.%s); if (bytes.Length > 0) w.Tag(%d, 2).Bytes(bytes); }", f.ProtoType, name, f.ProtoTag)
			continue
		}
		wt := protoWireType[f.ProtoType]
		wm := protoCSWriterMethod[f.ProtoType]
		if f.ProtoType == "bytes" {
			w("            if (m.%s.Length > 0) w.Tag(%d, %d).%s(m.%s);", name, f.ProtoTag, wt, wm, name)
		} else {
			w("            if (m.%s != %s) w.Tag(%d, %d).%s(m.%s);", name, protoCSZero[f.ProtoType], f.ProtoTag, wt, wm, name)
		}
	}
	w("            return w.Finish();")
	w("        }")
	w("")
	w("        public static %sEvent Decode(byte[] bytes)", ev.Name)
	w("        {")
	w("            var r = new PbReader(bytes);")
	w("            var m = new %sEvent();", ev.Name)
	w("            while (!r.Done)")
	w("            {")
	w("                var tag = r.Tag();")
	w("                switch (tag.Field)")
	w("                {")
	if ev.EntityType != "" {
		w("                    case 1: m.EntityId = r.Int64(); break;")
	}
	for _, f := range ev.Fields {
		name := schema.SnakeToPascal(f.SnakeName)
		if f.IsCustom {
			w("                    case %d: m.%s = %s.Decode(r.Bytes()); break;", f.ProtoTag, name, f.ProtoType)
		} else {
			w("                    case %d: m.%s = r.%s(); break;", f.ProtoTag, name, protoCSReaderMethod[f.ProtoType])
		}
	}
	w("                    default: r.Skip(tag.Wire); break;")
	w("                }")
	w("            }")
	w("            return m;")
	w("        }")
	w("    }")
	w("")
}

func writeCSServerEventClass(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("    public sealed class ServerEvent")
	w("    {")
	for _, sef := range proto.ServerEventFields {
		w("        public %s %s { get; set; }", sef.MessageType, schema.SnakeToPascal(sef.SnakeName))
	}
	w("")
	w("        public static ServerEvent Decode(byte[] bytes)")
	w("        {")
	w("            var r = new PbReader(bytes);")
	w("            var m = new ServerEvent();")
	w("            while (!r.Done)")
	w("            {")
	w("                var tag = r.Tag();")
	w("                switch (tag.Field)")
	w("                {")
	for _, sef := range proto.ServerEventFields {
		w("                    case %d: m.%s = %s.Decode(r.Bytes()); break;", sef.Tag, schema.SnakeToPascal(sef.SnakeName), sef.MessageType)
	}
	w("                    default: r.Skip(tag.Wire); break;")
	w("                }")
	w("            }")
	w("            return m;")
	w("        }")
	w("    }")
	w("")
}

func csharpNamespace(goPackage string) string {
	if strings.TrimSpace(goPackage) == "" {
		return "Golem.Generated"
	}
	return goPackage
}
