package codegen

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/demiurgos-hub/golem-engine/schema"
)

const entityRevisionProtoTag = 1000

func entityProtoTag(ent schema.EntityData, userTag int) int {
	dimensions := ent.Dimensions
	if dimensions == 0 {
		dimensions = 2
	}
	return userTag + dimensions + 1
}

// goWriterMethod maps protobuf scalar type names to pb.Writer method names.
var goWriterMethod = map[string]string{
	"double": "Float64",
	"float":  "Float32",
	"int32":  "Int32",
	"int64":  "Int64",
	"uint32": "Uint32",
	"uint64": "Uint64",
	"sint32": "Sint32",
	"sint64": "Sint64",
	"bool":   "Bool",
	"string": "String",
	"bytes":  "Bytes",
}

// goZeroExpr returns the Go zero-value expression for "if m.Field != <zero>"
// guards. Bool and bytes use special patterns handled inline.
var goZeroExpr = map[string]string{
	"double": "0",
	"float":  "0",
	"int32":  "0",
	"int64":  "0",
	"uint32": "0",
	"uint64": "0",
	"sint32": "0",
	"sint64": "0",
	"bool":   "",
	"string": `""`,
	"bytes":  "",
}

// goPointerType maps proto types to the Go pointer-dereference type suffix used
// in Delta Unmarshal. E.g. for "double" we emit "v := r.Float64(); m.X = &v".
var goPointerHelper = map[string]string{
	"double": "Float64",
	"float":  "Float32",
	"int32":  "Int32",
	"int64":  "Int64",
	"uint32": "Uint32",
	"uint64": "Uint64",
	"sint32": "Int32",
	"sint64": "Int64",
	"bool":   "Bool",
	"string": "String",
}

// generateGoProto writes entities_pb.go into outDir with Go message structs,
// Marshal/Unmarshal methods, and oneof wrappers for EntityUpdate and ClientMessage.
func generateGoProto(
	outDir string,
	golemImport string,
	goPackage string,
	entities []schema.EntityData,
	commands []schema.CommandData,
	worldTypes []schema.WorldTypeData,
	events []schema.EventData,
	proto schema.ProtoTemplateData,
) error {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("// GENERATED by Golem Engine — do not edit.")
	w("package %s", goPackage)
	w("")
	w("import (")
	w("\t\"fmt\"")
	w("")
	w("\t\"%s/pb\"", golemImport)
	w(")")

	for _, ct := range proto.CustomTypes {
		writeGoCustomTypeStruct(&b, ct)
	}

	for _, ent := range entities {
		writeGoStateStruct(&b, ent)
		writeGoDeltaStruct(&b, ent)
	}

	writeGoEntityRemoved(&b)
	writeGoEntityUpdate(&b, proto)

	for _, cmd := range commands {
		writeGoCommandStruct(&b, cmd)
	}

	if len(commands) > 0 {
		writeGoClientMessage(&b, proto)
		writeGoClientPacket(&b)
	}

	outPath := filepath.Join(outDir, "entities_pb.go")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("creating dir for %s: %w", outPath, err)
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	cmd := exec.Command("gofmt", "-w", outPath)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gofmt %s: %w\n%s", outPath, err, out)
	}
	fmt.Printf("  wrote %s\n", outPath)

	if len(worldTypes) > 0 {
		if err := generateGoWorldProto(outDir, golemImport, goPackage, proto); err != nil {
			return err
		}
	}
	if len(events) > 0 {
		if err := generateGoEventProto(outDir, golemImport, goPackage, proto); err != nil {
			return err
		}
	}
	return nil
}

// --- State struct (all fields, required) ---

func writeGoStateStruct(b *strings.Builder, ent schema.EntityData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("")
	w("type %sState struct {", ent.Name)
	w("\tEntityId int64")
	w("\tPosX float32")
	w("\tPosY float32")
	if ent.Is3D {
		w("\tPosZ float32")
	}
	w("\tRevision uint64")
	for _, v := range ent.AllVars {
		w("\t%s %s", v.GoName, v.GoType)
	}
	w("}")

	// Marshal
	w("")
	w("// Marshal encodes the state to protobuf wire format.")
	w("func (m *%sState) Marshal() []byte {", ent.Name)
	w("\tw := &pb.Writer{}")
	writeGoFieldEncode(b, "EntityId", "int64", 1, false)
	writeGoFieldEncode(b, "PosX", "float", 2, false)
	writeGoFieldEncode(b, "PosY", "float", 3, false)
	if ent.Is3D {
		writeGoFieldEncode(b, "PosZ", "float", 4, false)
	}
	writeGoFieldEncode(b, "Revision", "uint64", entityRevisionProtoTag, false)
	for _, v := range ent.AllVars {
		if v.IsRepeated || v.IsMap {
			writeGoCollectionMarshal(b, v, entityProtoTag(ent, v.UserTag), false)
		} else {
			writeGoFieldEncode(b, v.GoName, v.ProtoType, entityProtoTag(ent, v.UserTag), false)
		}
	}
	w("\treturn w.Finish()")
	w("}")

	// Unmarshal
	w("")
	w("// Unmarshal decodes the state from protobuf wire format.")
	w("func (m *%sState) Unmarshal(data []byte) (retErr error) {", ent.Name)
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode %sState: %%v\", r) } }()", ent.Name)
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	w("\t\tcase 1: m.EntityId = rd.Int64()")
	w("\t\tcase 2: m.PosX = rd.Float32()")
	w("\t\tcase 3: m.PosY = rd.Float32()")
	if ent.Is3D {
		w("\t\tcase 4: m.PosZ = rd.Float32()")
	}
	w("\t\tcase %d: m.Revision = rd.Uint64()", entityRevisionProtoTag)
	for _, v := range ent.AllVars {
		if v.IsRepeated || v.IsMap {
			writeGoCollectionUnmarshal(b, v, entityProtoTag(ent, v.UserTag), false)
		} else {
			w("\t\tcase %d: m.%s = rd.%s()", entityProtoTag(ent, v.UserTag), v.GoName, goWriterMethod[v.ProtoType])
		}
	}
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// --- Delta struct (tick vars as pointers for optional semantics) ---

func writeGoDeltaStruct(b *strings.Builder, ent schema.EntityData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("")
	w("type %sDelta struct {", ent.Name)
	w("\tEntityId int64")
	w("\tPosX *float32")
	w("\tPosY *float32")
	if ent.Is3D {
		w("\tPosZ *float32")
	}
	w("\tRevision uint64")
	for _, v := range ent.TickVars {
		if v.IsRepeated || v.IsMap {
			// nil slice/map = absent; non-nil (even empty) = field was changed this tick
			w("\t%s %s", v.GoName, v.GoType)
		} else {
			w("\t%s *%s", v.GoName, v.GoType)
		}
	}
	w("}")

	// Marshal
	w("")
	w("// Marshal encodes the delta to protobuf wire format.")
	w("func (m *%sDelta) Marshal() []byte {", ent.Name)
	w("\tw := &pb.Writer{}")
	writeGoFieldEncode(b, "EntityId", "int64", 1, false)
	writeGoFieldEncode(b, "PosX", "float", 2, true)
	writeGoFieldEncode(b, "PosY", "float", 3, true)
	if ent.Is3D {
		writeGoFieldEncode(b, "PosZ", "float", 4, true)
	}
	writeGoFieldEncode(b, "Revision", "uint64", entityRevisionProtoTag, false)
	for _, v := range ent.TickVars {
		if v.IsRepeated || v.IsMap {
			writeGoCollectionMarshal(b, v, entityProtoTag(ent, v.UserTag), true)
		} else {
			writeGoFieldEncode(b, v.GoName, v.ProtoType, entityProtoTag(ent, v.UserTag), true)
		}
	}
	w("\treturn w.Finish()")
	w("}")

	// Unmarshal
	w("")
	w("// Unmarshal decodes the delta from protobuf wire format.")
	w("func (m *%sDelta) Unmarshal(data []byte) (retErr error) {", ent.Name)
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode %sDelta: %%v\", r) } }()", ent.Name)
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	w("\t\tcase 1: m.EntityId = rd.Int64()")
	w("\t\tcase 2:")
	w("\t\t\tv := rd.Float32()")
	w("\t\t\tm.PosX = &v")
	w("\t\tcase 3:")
	w("\t\t\tv := rd.Float32()")
	w("\t\t\tm.PosY = &v")
	if ent.Is3D {
		w("\t\tcase 4:")
		w("\t\t\tv := rd.Float32()")
		w("\t\t\tm.PosZ = &v")
	}
	w("\t\tcase %d: m.Revision = rd.Uint64()", entityRevisionProtoTag)
	for _, v := range ent.TickVars {
		if v.IsRepeated || v.IsMap {
			writeGoCollectionUnmarshal(b, v, entityProtoTag(ent, v.UserTag), true)
		} else {
			w("\t\tcase %d:", entityProtoTag(ent, v.UserTag))
			w("\t\t\tv := rd.%s()", goWriterMethod[v.ProtoType])
			w("\t\t\tm.%s = &v", v.GoName)
		}
	}
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// --- EntityRemoved ---

func writeGoEntityRemoved(b *strings.Builder) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("")
	w("type EntityRemoved struct {")
	w("\tEntityId int64")
	w("\tRevision uint64")
	w("}")
	w("")
	w("// Marshal encodes the removal marker to protobuf wire format.")
	w("func (m *EntityRemoved) Marshal() []byte {")
	w("\tw := &pb.Writer{}")
	w("\tif m.EntityId != 0 { w.Tag(1, 0).Int64(m.EntityId) }")
	w("\tif m.Revision != 0 { w.Tag(%d, 0).Uint64(m.Revision) }", entityRevisionProtoTag)
	w("\treturn w.Finish()")
	w("}")
	w("")
	w("// Unmarshal decodes the removal marker from protobuf wire format.")
	w("func (m *EntityRemoved) Unmarshal(data []byte) (retErr error) {")
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode EntityRemoved: %%v\", r) } }()")
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	w("\t\tcase 1: m.EntityId = rd.Int64()")
	w("\t\tcase %d: m.Revision = rd.Uint64()", entityRevisionProtoTag)
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// --- EntityUpdate (oneof: State/Delta per entity + EntityRemoved) ---

func writeGoEntityUpdate(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	// Interface
	w("")
	w("type isEntityUpdatePayload interface { isEntityUpdatePayload() }")
	w("")
	w("// EntityUpdate wraps a single State, Delta, or EntityRemoved payload.")
	w("type EntityUpdate struct { Payload isEntityUpdatePayload }")

	// Variant types
	for _, uf := range proto.EntityUpdateFields {
		w("")
		w("// EntityUpdate_%s is the oneof wrapper for %s.", uf.MessageType, uf.MessageType)
		w("type EntityUpdate_%s struct { %s *%s }", uf.MessageType, uf.MessageType, uf.MessageType)
		w("func (*EntityUpdate_%s) isEntityUpdatePayload() {}", uf.MessageType)
	}
	w("")
	w("// EntityUpdate_EntityRemoved is the oneof wrapper for EntityRemoved.")
	w("type EntityUpdate_EntityRemoved struct { EntityRemoved *EntityRemoved }")
	w("func (*EntityUpdate_EntityRemoved) isEntityUpdatePayload() {}")

	// Marshal
	w("")
	w("// Marshal encodes the update to protobuf wire format.")
	w("func (m *EntityUpdate) Marshal() []byte {")
	w("\tw := &pb.Writer{}")
	w("\tswitch p := m.Payload.(type) {")
	for _, uf := range proto.EntityUpdateFields {
		w("\tcase *EntityUpdate_%s:", uf.MessageType)
		w("\t\tw.Tag(%d, 2).Bytes(p.%s.Marshal())", uf.Tag, uf.MessageType)
	}
	w("\tcase *EntityUpdate_EntityRemoved:")
	w("\t\tw.Tag(%d, 2).Bytes(p.EntityRemoved.Marshal())", proto.EntityRemovedTag)
	w("\t}")
	w("\treturn w.Finish()")
	w("}")

	// Unmarshal
	w("")
	w("// Unmarshal decodes the update from protobuf wire format.")
	w("func (m *EntityUpdate) Unmarshal(data []byte) (retErr error) {")
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode EntityUpdate: %%v\", r) } }()")
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	for _, uf := range proto.EntityUpdateFields {
		w("\t\tcase %d:", uf.Tag)
		w("\t\t\tsub := &%s{}", uf.MessageType)
		w("\t\t\tif err := sub.Unmarshal(rd.Bytes()); err != nil { return err }")
		w("\t\t\tm.Payload = &EntityUpdate_%s{%s: sub}", uf.MessageType, uf.MessageType)
	}
	w("\t\tcase %d:", proto.EntityRemovedTag)
	w("\t\t\tsub := &EntityRemoved{}")
	w("\t\t\tif err := sub.Unmarshal(rd.Bytes()); err != nil { return err }")
	w("\t\t\tm.Payload = &EntityUpdate_EntityRemoved{EntityRemoved: sub}")
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// --- Command structs ---

func writeGoCommandStruct(b *strings.Builder, cmd schema.CommandData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("")
	w("type %sCommand struct {", cmd.Name)
	if cmd.Target == "entity" {
		w("\tEntityId int64")
	}
	for _, f := range cmd.Fields {
		w("\t%s %s", f.GoName, f.GoType)
	}
	w("}")

	// Marshal
	w("")
	w("// Marshal encodes the command to protobuf wire format.")
	w("func (m *%sCommand) Marshal() []byte {", cmd.Name)
	w("\tw := &pb.Writer{}")
	if cmd.Target == "entity" {
		writeGoFieldEncode(b, "EntityId", "int64", 1, false)
	}
	for _, f := range cmd.Fields {
		if f.IsCustom {
			w("\tif _b := m.%s.Marshal(); len(_b) > 0 { w.Tag(%d, 2).Bytes(_b) }", f.GoName, f.ProtoTag)
		} else {
			writeGoFieldEncode(b, f.GoName, f.ProtoType, f.ProtoTag, false)
		}
	}
	w("\treturn w.Finish()")
	w("}")

	// Unmarshal
	w("")
	w("// Unmarshal decodes the command from protobuf wire format.")
	w("func (m *%sCommand) Unmarshal(data []byte) (retErr error) {", cmd.Name)
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode %sCommand: %%v\", r) } }()", cmd.Name)
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	if cmd.Target == "entity" {
		w("\t\tcase 1: m.EntityId = rd.Int64()")
	}
	for _, f := range cmd.Fields {
		if f.IsCustom {
			w("\t\tcase %d:", f.ProtoTag)
			w("\t\t\tvar _sub %s", f.GoType)
			w("\t\t\tif _err := _sub.Unmarshal(rd.Bytes()); _err != nil { return _err }")
			w("\t\t\tm.%s = _sub", f.GoName)
		} else {
			w("\t\tcase %d: m.%s = rd.%s()", f.ProtoTag, f.GoName, goWriterMethod[f.ProtoType])
		}
	}
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// --- ClientMessage (oneof wrapper for commands) ---

func writeGoClientMessage(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	// Interface
	w("")
	w("type isClientMessagePayload interface { isClientMessagePayload() }")
	w("")
	w("// ClientMessage wraps a single command payload sent by the client.")
	w("type ClientMessage struct { Payload isClientMessagePayload }")

	// Variant types
	for _, cmf := range proto.ClientMessageFields {
		w("")
		w("// ClientMessage_%s is the oneof wrapper for %s.", cmf.MessageType, cmf.MessageType)
		w("type ClientMessage_%s struct { %s *%s }", cmf.MessageType, cmf.MessageType, cmf.MessageType)
		w("func (*ClientMessage_%s) isClientMessagePayload() {}", cmf.MessageType)
	}

	// Marshal
	w("")
	w("// Marshal encodes the client message to protobuf wire format.")
	w("func (m *ClientMessage) Marshal() []byte {")
	w("\tw := &pb.Writer{}")
	w("\tswitch p := m.Payload.(type) {")
	for _, cmf := range proto.ClientMessageFields {
		w("\tcase *ClientMessage_%s:", cmf.MessageType)
		w("\t\tw.Tag(%d, 2).Bytes(p.%s.Marshal())", cmf.Tag, cmf.MessageType)
	}
	w("\t}")
	w("\treturn w.Finish()")
	w("}")

	// Unmarshal
	w("")
	w("// Unmarshal decodes a client message from protobuf wire format.")
	w("func (m *ClientMessage) Unmarshal(data []byte) (retErr error) {")
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode ClientMessage: %%v\", r) } }()")
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	for _, cmf := range proto.ClientMessageFields {
		w("\t\tcase %d:", cmf.Tag)
		w("\t\t\tsub := &%s{}", cmf.MessageType)
		w("\t\t\tif err := sub.Unmarshal(rd.Bytes()); err != nil { return err }")
		w("\t\t\tm.Payload = &ClientMessage_%s{%s: sub}", cmf.MessageType, cmf.MessageType)
	}
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// writeGoClientPacket emits a transport envelope that batches multiple encoded
// ClientMessage blobs into one reliable message payload.
func writeGoClientPacket(b *strings.Builder) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("")
	w("// ClientPacket batches one or more encoded ClientMessage blobs.")
	w("type ClientPacket struct { Frames [][]byte }")
	w("")
	w("// Marshal encodes the client packet to protobuf wire format.")
	w("func (m *ClientPacket) Marshal() []byte {")
	w("\tw := &pb.Writer{}")
	w("\tfor _, frame := range m.Frames {")
	w("\t\tw.Tag(1, 2).Bytes(frame)")
	w("\t}")
	w("\treturn w.Finish()")
	w("}")
	w("")
	w("// Unmarshal decodes a client packet from protobuf wire format.")
	w("func (m *ClientPacket) Unmarshal(data []byte) (retErr error) {")
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode ClientPacket: %%v\", r) } }()")
	w("\trd := pb.NewReader(data)")
	w("\tm.Frames = m.Frames[:0]")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	w("\t\tcase 1:")
	w("\t\t\tframe := append([]byte(nil), rd.Bytes()...)")
	w("\t\t\tm.Frames = append(m.Frames, frame)")
	w("\t\tdefault:")
	w("\t\t\trd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// --- Event structs ---

// generateGoEventProto writes events_pb.go into outDir with per-event structs
// (Marshal/Unmarshal) and the ServerEvent oneof wrapper.
func generateGoEventProto(outDir, golemImport, goPackage string, proto schema.ProtoTemplateData) error {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("// GENERATED by Golem Engine — do not edit.")
	w("package %s", goPackage)
	w("")
	w("import (")
	w("\t\"fmt\"")
	w("")
	w("\t\"%s/pb\"", golemImport)
	w(")")

	for _, ev := range proto.Events {
		writeGoEventStruct(&b, ev)
	}

	writeGoServerEvent(&b, proto)

	outPath := filepath.Join(outDir, "events_pb.go")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	cmd := exec.Command("gofmt", "-w", outPath)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gofmt %s: %w\n%s", outPath, err, out)
	}
	fmt.Printf("  wrote %s\n", outPath)
	return nil
}

// writeGoEventStruct emits a struct with Marshal/Unmarshal for a single event type.
// When EntityType is set, EntityId is the first field (proto tag 1) and user fields start at 2.
func writeGoEventStruct(b *strings.Builder, ev schema.EventData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }
	structName := ev.Name + "Event"

	w("")
	w("type %s struct {", structName)
	if ev.EntityType != "" {
		w("\tEntityId int64")
	}
	for _, f := range ev.Fields {
		w("\t%s %s", f.GoName, f.GoType)
	}
	w("}")

	// Marshal
	w("")
	w("// Marshal encodes the event to protobuf wire format.")
	w("func (m *%s) Marshal() []byte {", structName)
	w("\tw := &pb.Writer{}")
	if ev.EntityType != "" {
		writeGoFieldEncode(b, "EntityId", "int64", 1, false)
	}
	for _, f := range ev.Fields {
		if f.IsCustom {
			w("\tif _b := m.%s.Marshal(); len(_b) > 0 { w.Tag(%d, 2).Bytes(_b) }", f.GoName, f.ProtoTag)
		} else {
			writeGoFieldEncode(b, f.GoName, f.ProtoType, f.ProtoTag, false)
		}
	}
	w("\treturn w.Finish()")
	w("}")

	// Unmarshal
	w("")
	w("// Unmarshal decodes the event from protobuf wire format.")
	w("func (m *%s) Unmarshal(data []byte) (retErr error) {", structName)
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode %s: %%v\", r) } }()", structName)
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	if ev.EntityType != "" {
		w("\t\tcase 1: m.EntityId = rd.Int64()")
	}
	for _, f := range ev.Fields {
		if f.IsCustom {
			w("\t\tcase %d:", f.ProtoTag)
			w("\t\t\tvar _sub %s", f.GoType)
			w("\t\t\tif _err := _sub.Unmarshal(rd.Bytes()); _err != nil { return _err }")
			w("\t\t\tm.%s = _sub", f.GoName)
		} else {
			w("\t\tcase %d: m.%s = rd.%s()", f.ProtoTag, f.GoName, goWriterMethod[f.ProtoType])
		}
	}
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// writeGoServerEvent emits the ServerEvent oneof struct (Marshal/Unmarshal).
func writeGoServerEvent(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("")
	w("type isServerEventPayload interface { isServerEventPayload() }")
	w("")
	w("// ServerEvent wraps a single server-to-client event payload.")
	w("type ServerEvent struct { Payload isServerEventPayload }")

	for _, sef := range proto.ServerEventFields {
		w("")
		w("// ServerEvent_%s is the oneof wrapper for %s.", sef.MessageType, sef.MessageType)
		w("type ServerEvent_%s struct { %s *%s }", sef.MessageType, sef.MessageType, sef.MessageType)
		w("func (*ServerEvent_%s) isServerEventPayload() {}", sef.MessageType)
	}

	// Marshal
	w("")
	w("// Marshal encodes the server event to protobuf wire format.")
	w("func (m *ServerEvent) Marshal() []byte {")
	w("\tw := &pb.Writer{}")
	w("\tswitch p := m.Payload.(type) {")
	for _, sef := range proto.ServerEventFields {
		w("\tcase *ServerEvent_%s:", sef.MessageType)
		w("\t\tw.Tag(%d, 2).Bytes(p.%s.Marshal())", sef.Tag, sef.MessageType)
	}
	w("\t}")
	w("\treturn w.Finish()")
	w("}")

	// Unmarshal
	w("")
	w("// Unmarshal decodes a server event from protobuf wire format.")
	w("func (m *ServerEvent) Unmarshal(data []byte) (retErr error) {")
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode ServerEvent: %%v\", r) } }()")
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	for _, sef := range proto.ServerEventFields {
		w("\t\tcase %d:", sef.Tag)
		w("\t\t\tsub := &%s{}", sef.MessageType)
		w("\t\t\tif err := sub.Unmarshal(rd.Bytes()); err != nil { return err }")
		w("\t\t\tm.Payload = &ServerEvent_%s{%s: sub}", sef.MessageType, sef.MessageType)
	}
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// --- World data structs ---

// generateGoWorldProto writes world_pb.go into outDir with per-world-type
// structs (implementing world.Data) and the WorldUpdate oneof.
func generateGoWorldProto(outDir, golemImport, goPackage string, proto schema.ProtoTemplateData) error {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	// Determine which extra imports are needed based on source: declarations.
	needOS := false
	needFilepath := false
	needTiled := false
	needLDtk := false
	needYAML := false
	for _, wt := range proto.WorldTypes {
		if wt.Source == nil {
			continue
		}
		needOS = true
		if wt.Source.URLPrefix != "" {
			needFilepath = true
		}
		switch wt.Source.Format {
		case "tiled":
			needTiled = true
		case "ldtk":
			needLDtk = true
		case "catalog":
			needYAML = true
		}
	}

	w("// GENERATED by Golem Engine — do not edit.")
	w("package %s", goPackage)
	w("")
	w("import (")
	w("\t\"fmt\"")
	if needOS {
		w("\t\"os\"")
	}
	if needFilepath {
		w("\t\"path/filepath\"")
	}
	if needYAML {
		w("\t\"strconv\"")
	}
	w("")
	w("\t\"%s/pb\"", golemImport)
	if needTiled {
		w("\t\"%s/tiled\"", golemImport)
	}
	if needLDtk {
		w("\t\"%s/ldtk\"", golemImport)
	}
	if needYAML {
		w("\t\"gopkg.in/yaml.v3\"")
	}
	w(")")

	for i, wt := range proto.WorldTypes {
		writeGoWorldDataStruct(&b, wt, proto.WorldUpdateFields[i])
		if wt.Source != nil {
			customTypesMap := make(map[string]schema.CustomTypeData, len(proto.CustomTypes))
			for _, ct := range proto.CustomTypes {
				customTypesMap[ct.Name] = ct
			}
			writeGoWorldLoader(&b, wt, customTypesMap)
		}
	}

	writeGoWorldUpdate(&b, proto)

	outPath := filepath.Join(outDir, "world_pb.go")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	cmd := exec.Command("gofmt", "-w", outPath)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gofmt %s: %w\n%s", outPath, err, out)
	}
	fmt.Printf("  wrote %s\n", outPath)
	return nil
}

// writeGoWorldDataStruct emits a world data struct with Marshal, MarshalUpdate,
// Unmarshal, and WorldName. wuf.Tag is the oneof tag inside WorldUpdate.
func writeGoWorldDataStruct(b *strings.Builder, wt schema.WorldTypeData, wuf schema.WorldUpdateField) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("")
	w("// %s holds static world data for %q.", wt.DataName, wt.Name)
	w("type %s struct {", wt.DataName)
	for _, f := range wt.Fields {
		w("\t%s %s", f.GoName, f.GoType)
	}
	w("}")

	w("")
	w("// WorldName returns the world type identifier.")
	w("func (m *%s) WorldName() string { return %q }", wt.DataName, wt.Name)

	// Marshal — raw inner bytes
	w("")
	w("// Marshal encodes the data to protobuf wire format (inner bytes only).")
	w("func (m *%s) Marshal() []byte {", wt.DataName)
	w("\tw := &pb.Writer{}")
	for _, f := range wt.Fields {
		if f.IsRepeated || f.IsMap {
			writeGoWorldFieldCollectionMarshal(b, f)
		} else {
			writeGoFieldEncode(b, f.GoName, f.ProtoType, f.ProtoTag, false)
		}
	}
	w("\treturn w.Finish()")
	w("}")

	// MarshalUpdate — wrapped in WorldUpdate oneof
	w("")
	w("// MarshalUpdate encodes the data wrapped in a WorldUpdate oneof envelope.")
	w("func (m *%s) MarshalUpdate() ([]byte, error) {", wt.DataName)
	w("\tinner := m.Marshal()")
	w("\tw := &pb.Writer{}")
	w("\tw.Tag(%d, 2).Bytes(inner)", wuf.Tag)
	w("\treturn w.Finish(), nil")
	w("}")

	// Unmarshal
	w("")
	w("// Unmarshal decodes the data from protobuf wire format.")
	w("func (m *%s) Unmarshal(data []byte) (retErr error) {", wt.DataName)
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode %s: %%v\", r) } }()", wt.DataName)
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	for _, f := range wt.Fields {
		if f.IsRepeated || f.IsMap {
			writeGoWorldFieldCollectionUnmarshal(b, f)
		} else {
			w("\t\tcase %d: m.%s = rd.%s()", f.ProtoTag, f.GoName, goWriterMethod[f.ProtoType])
		}
	}
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// writeGoWorldFieldCollectionMarshal emits marshal code for a collection WorldFieldInfo.
func writeGoWorldFieldCollectionMarshal(b *strings.Builder, f schema.WorldFieldInfo) {
	w := func(fmt_ string, a ...any) { fmt.Fprintf(b, fmt_+"\n", a...) }
	tag := f.ProtoTag
	if f.IsRepeated {
		w("\tfor _, _elem := range m.%s {", f.GoName)
		if f.ElemIsCustom {
			fmt.Fprintf(b, "\t\tw.Tag(%d, 2).Bytes(_elem.Marshal())\n", tag)
		} else {
			fmt.Fprintf(b, "{ _inner := &pb.Writer{}; _inner.%s(_elem); w.Tag(%d, 2).Bytes(_inner.Finish()) }\n",
				goWriterMethod[f.ElemProtoType], tag)
		}
		w("\t}")
	} else { // IsMap
		w("\tfor _k, _v := range m.%s {", f.GoName)
		keyWT := protoWireType[f.MapKeyProtoType]
		keyWM := goWriterMethod[f.MapKeyProtoType]
		w("\t\t_kv := &pb.Writer{}")
		w("\t\t_kv.Tag(1, %d).%s(_k)", keyWT, keyWM)
		if f.ElemIsCustom {
			w("\t\t_kv.Tag(2, 2).Bytes(_v.Marshal())")
		} else {
			valWT := protoWireType[f.ElemProtoType]
			valWM := goWriterMethod[f.ElemProtoType]
			w("\t\t_kv.Tag(2, %d).%s(_v)", valWT, valWM)
		}
		w("\t\tw.Tag(%d, 2).Bytes(_kv.Finish())", tag)
		w("\t}")
	}
}

// writeGoWorldFieldCollectionUnmarshal emits unmarshal case code for a collection WorldFieldInfo.
func writeGoWorldFieldCollectionUnmarshal(b *strings.Builder, f schema.WorldFieldInfo) {
	w := func(fmt_ string, a ...any) { fmt.Fprintf(b, fmt_+"\n", a...) }
	w("\t\tcase %d:", f.ProtoTag)
	if f.IsRepeated {
		w("\t\t\t_b := rd.Bytes()")
		w("\t\t\tif len(_b) > 0 {")
		if f.ElemIsCustom {
			w("\t\t\t\tvar _elem %s", f.ElemProtoType)
			w("\t\t\t\tif _err := _elem.Unmarshal(_b); _err != nil { return _err }")
			w("\t\t\t\tm.%s = append(m.%s, _elem)", f.GoName, f.GoName)
		} else {
			w("\t\t\t\t_inner := pb.NewReader(_b)")
			w("\t\t\t\tm.%s = append(m.%s, _inner.%s())", f.GoName, f.GoName, goWriterMethod[f.ElemProtoType])
		}
		w("\t\t\t}")
	} else { // IsMap
		w("\t\t\t_b := rd.Bytes()")
		w("\t\t\tif len(_b) > 0 {")
		w("\t\t\t\t_rd := pb.NewReader(_b)")
		w("\t\t\t\tvar _k %s", f.MapKeyGoType)
		w("\t\t\t\tvar _v %s", f.ElemGoType)
		w("\t\t\t\tfor !_rd.Done() {")
		w("\t\t\t\t\t_f, _ := _rd.Tag()")
		w("\t\t\t\t\tswitch _f {")
		w("\t\t\t\t\tcase 1: _k = _rd.%s()", goWriterMethod[f.MapKeyProtoType])
		if f.ElemIsCustom {
			w("\t\t\t\t\tcase 2:")
			w("\t\t\t\t\t\tif _err := _v.Unmarshal(_rd.Bytes()); _err != nil { return _err }")
		} else {
			w("\t\t\t\t\tcase 2: _v = _rd.%s()", goWriterMethod[f.ElemProtoType])
		}
		w("\t\t\t\t\t}")
		w("\t\t\t\t}")
		w("\t\t\t\tif m.%s == nil { m.%s = %s{} }", f.GoName, f.GoName, f.GoType)
		w("\t\t\t\tm.%s[_k] = _v", f.GoName)
		w("\t\t\t} else {")
		w("\t\t\t\tif m.%s == nil { m.%s = %s{} }", f.GoName, f.GoName, f.GoType)
		w("\t\t\t}")
	}
}

// writeGoWorldLoader emits a LoadXxxData(path string) helper for world types
// that have a source: block. For Tiled sources, custom properties are extracted
// from Map.Properties; for LDtk sources, from the first level's FieldInstances.
// For catalog sources, entries are read from a YAML sequence and populated into
// a list or dict field. When url_prefix is set, MapUrl is populated and raw
// bytes are not embedded; otherwise TileData receives the full raw file contents.
func writeGoWorldLoader(b *strings.Builder, wt schema.WorldTypeData, customTypes map[string]schema.CustomTypeData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }
	src := wt.Source

	if src.Format == "catalog" {
		writeGoWorldCatalogLoader(b, wt, customTypes)
		return
	}

	w("")
	w("// Load%s reads the %s map file at path, populates extracted custom", wt.DataName, src.Format)
	w("// properties, and returns a %s ready to store in the world.Store.", wt.DataName)
	w("func Load%s(path string) (*%s, error) {", wt.DataName, wt.DataName)
	w("\traw, err := os.ReadFile(path)")
	w("\tif err != nil { return nil, err }")

	switch src.Format {
	case "tiled":
		w("\tm, err := tiled.Parse(raw)")
		w("\tif err != nil { return nil, err }")
	case "ldtk":
		w("\tproj, err := ldtk.Parse(raw)")
		w("\tif err != nil { return nil, err }")
	}

	w("\td := &%s{}", wt.DataName)

	// Set the synthetic tile_data or map_url field.
	if src.URLPrefix != "" {
		w("\td.MapUrl = %q + filepath.Base(path)", src.URLPrefix)
	} else {
		w("\td.TileData = raw")
	}

	// Emit property extraction for each declared extract field.
	for _, ex := range src.Extract {
		goName := schema.SnakeToPascal(ex.Name)
		switch src.Format {
		case "tiled":
			w("\tif p, ok := m.PropertyByName(%q); ok {", ex.Name)
			w("\t\td.%s = %s", goName, tiledPropertyConvert(ex.Type, "p"))
			w("\t}")
		case "ldtk":
			w("\tlevels := proj.AllLevels()")
			w("\tif len(levels) > 0 {")
			w("\t\tif f := levels[0].FieldByIdentifier(%q); f != nil {", ex.Name)
			w("\t\t\td.%s = %s", goName, ldtkFieldConvert(ex.Type, "f"))
			w("\t\t}")
			w("\t}")
		}
	}

	w("\treturn d, nil")
	w("}")
}

// writeGoWorldCatalogLoader emits a LoadXxxData(path string) helper for catalog
// world types. It reads a YAML sequence, converts each entry map to the custom
// type struct, and appends to a list or inserts into a map.
func writeGoWorldCatalogLoader(b *strings.Builder, wt schema.WorldTypeData, customTypes map[string]schema.CustomTypeData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }
	src := wt.Source

	ct := customTypes[src.Type]

	w("")
	w("// Load%s reads the catalog YAML at path and returns a %s ready to store in the world.Store.", wt.DataName, wt.DataName)
	w("func Load%s(path string) (*%s, error) {", wt.DataName, wt.DataName)
	w("\traw, err := os.ReadFile(path)")
	w("\tif err != nil { return nil, err }")
	w("\tvar _rows []map[string]any")
	w("\tif err := yaml.Unmarshal(raw, &_rows); err != nil { return nil, err }")
	w("\td := &%s{}", wt.DataName)
	if src.Key != "" {
		// Determine key Go type for make()
		keyGoType := ""
		for _, cf := range ct.Fields {
			if cf.SnakeName == src.Key {
				keyGoType = cf.GoType
				break
			}
		}
		w("\td.Items = make(map[%s]%s, len(_rows))", keyGoType, src.Type)
	}
	w("\tfor _, _row := range _rows {")
	w("\t\t_elem := %s{}", src.Type)
	for _, cf := range ct.Fields {
		w("\t\tif _fv, _ok := _row[%q]; _ok {", cf.SnakeName)
		w("\t\t\t%s", catalogYAMLConvert(cf.ProtoType, "_elem."+cf.GoName, "_fv"))
		w("\t\t}")
	}
	if src.Key == "" {
		w("\t\td.Items = append(d.Items, _elem)")
	} else {
		keyGoName := schema.SnakeToPascal(src.Key)
		w("\t\td.Items[_elem.%s] = _elem", keyGoName)
	}
	w("\t}")
	w("\treturn d, nil")
	w("}")
}

// catalogYAMLConvert returns a Go statement that reads a YAML-decoded any value
// and assigns it to the target variable with appropriate type conversion.
func catalogYAMLConvert(protoType, target, src string) string {
	switch protoType {
	case "string":
		return fmt.Sprintf("if _s, _ok := %s.(string); _ok { %s = _s }", src, target)
	case "bool":
		return fmt.Sprintf("if _bv, _ok := %s.(bool); _ok { %s = _bv }", src, target)
	case "double":
		return fmt.Sprintf("switch _tv := %s.(type) { case float64: %s = _tv; case int: %s = float64(_tv); case string: if _n, _e := strconv.ParseFloat(_tv, 64); _e == nil { %s = _n } }", src, target, target, target)
	case "float":
		return fmt.Sprintf("switch _tv := %s.(type) { case float64: %s = float32(_tv); case int: %s = float32(_tv); case string: if _n, _e := strconv.ParseFloat(_tv, 32); _e == nil { %s = float32(_n) } }", src, target, target, target)
	case "int32", "sint32":
		return fmt.Sprintf("switch _tv := %s.(type) { case int: %s = int32(_tv); case int64: %s = int32(_tv); case float64: %s = int32(_tv); case string: if _n, _e := strconv.ParseInt(_tv, 10, 32); _e == nil { %s = int32(_n) } }", src, target, target, target, target)
	case "int64", "sint64":
		return fmt.Sprintf("switch _tv := %s.(type) { case int: %s = int64(_tv); case int64: %s = _tv; case float64: %s = int64(_tv); case string: if _n, _e := strconv.ParseInt(_tv, 10, 64); _e == nil { %s = _n } }", src, target, target, target, target)
	case "uint32":
		return fmt.Sprintf("switch _tv := %s.(type) { case int: %s = uint32(_tv); case int64: %s = uint32(_tv); case float64: %s = uint32(_tv); case string: if _n, _e := strconv.ParseUint(_tv, 10, 32); _e == nil { %s = uint32(_n) } }", src, target, target, target, target)
	case "uint64":
		return fmt.Sprintf("switch _tv := %s.(type) { case int: %s = uint64(_tv); case int64: %s = uint64(_tv); case float64: %s = uint64(_tv); case string: if _n, _e := strconv.ParseUint(_tv, 10, 64); _e == nil { %s = _n } }", src, target, target, target, target)
	default:
		return fmt.Sprintf("_ = %s // unsupported catalog field type %s", src, protoType)
	}
}

// tiledPropertyConvert returns a Go expression that converts a tiled.Property
// variable (named by varName) to the given proto type.
func tiledPropertyConvert(protoType, varName string) string {
	switch protoType {
	case "bool":
		return varName + ".BoolValue()"
	case "string":
		return varName + ".StringValue()"
	case "double":
		return varName + ".FloatValue()"
	case "float":
		return fmt.Sprintf("float32(%s.FloatValue())", varName)
	case "int32", "sint32":
		return fmt.Sprintf("int32(%s.IntValue())", varName)
	case "int64", "sint64":
		return fmt.Sprintf("int64(%s.IntValue())", varName)
	case "uint32":
		return fmt.Sprintf("uint32(%s.IntValue())", varName)
	case "uint64":
		return fmt.Sprintf("uint64(%s.IntValue())", varName)
	default:
		return fmt.Sprintf("/* unsupported type %s */ %s.StringValue()", protoType, varName)
	}
}

// ldtkFieldConvert returns a Go expression that converts an *ldtk.FieldInstance
// pointer (named by varName) to the given proto type.
func ldtkFieldConvert(protoType, varName string) string {
	switch protoType {
	case "bool":
		return varName + ".BoolValue()"
	case "string":
		return varName + ".StringValue()"
	case "double":
		return varName + ".FloatValue()"
	case "float":
		return fmt.Sprintf("float32(%s.FloatValue())", varName)
	case "int32", "sint32":
		return fmt.Sprintf("int32(%s.IntValue())", varName)
	case "int64", "sint64":
		return fmt.Sprintf("int64(%s.IntValue())", varName)
	case "uint32":
		return fmt.Sprintf("uint32(%s.IntValue())", varName)
	case "uint64":
		return fmt.Sprintf("uint64(%s.IntValue())", varName)
	default:
		return fmt.Sprintf("/* unsupported type %s */ %s.StringValue()", protoType, varName)
	}
}

// writeGoWorldUpdate emits the WorldUpdate oneof struct with Marshal/Unmarshal.
func writeGoWorldUpdate(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("")
	w("type isWorldUpdatePayload interface { isWorldUpdatePayload() }")
	w("")
	w("// WorldUpdate wraps a single world data payload.")
	w("type WorldUpdate struct { Payload isWorldUpdatePayload }")

	for _, wuf := range proto.WorldUpdateFields {
		w("")
		w("// WorldUpdate_%s is the oneof wrapper for %s.", wuf.MessageType, wuf.MessageType)
		w("type WorldUpdate_%s struct { %s *%s }", wuf.MessageType, wuf.MessageType, wuf.MessageType)
		w("func (*WorldUpdate_%s) isWorldUpdatePayload() {}", wuf.MessageType)
	}

	// Marshal
	w("")
	w("// Marshal encodes the world update to protobuf wire format.")
	w("func (m *WorldUpdate) Marshal() []byte {")
	w("\tw := &pb.Writer{}")
	w("\tswitch p := m.Payload.(type) {")
	for _, wuf := range proto.WorldUpdateFields {
		w("\tcase *WorldUpdate_%s:", wuf.MessageType)
		w("\t\tw.Tag(%d, 2).Bytes(p.%s.Marshal())", wuf.Tag, wuf.MessageType)
	}
	w("\t}")
	w("\treturn w.Finish()")
	w("}")

	// Unmarshal
	w("")
	w("// Unmarshal decodes the world update from protobuf wire format.")
	w("func (m *WorldUpdate) Unmarshal(data []byte) (retErr error) {")
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode WorldUpdate: %%v\", r) } }()")
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	for _, wuf := range proto.WorldUpdateFields {
		w("\t\tcase %d:", wuf.Tag)
		w("\t\t\tsub := &%s{}", wuf.MessageType)
		w("\t\t\tif err := sub.Unmarshal(rd.Bytes()); err != nil { return err }")
		w("\t\t\tm.Payload = &WorldUpdate_%s{%s: sub}", wuf.MessageType, wuf.MessageType)
	}
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// writeGoCustomTypeStruct emits the struct definition plus Marshal/Unmarshal for one custom type.
func writeGoCustomTypeStruct(b *strings.Builder, ct schema.CustomTypeData) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("")
	w("// %s is a custom composite type.", ct.Name)
	w("type %s struct {", ct.Name)
	for _, f := range ct.Fields {
		w("\t%s %s", f.GoName, f.GoType)
	}
	w("}")

	w("")
	w("// Marshal encodes %s to protobuf wire format.", ct.Name)
	w("func (m *%s) Marshal() []byte {", ct.Name)
	w("\tw := &pb.Writer{}")
	for _, f := range ct.Fields {
		writeGoFieldEncode(b, f.GoName, f.ProtoType, f.ProtoTag, false)
	}
	w("\treturn w.Finish()")
	w("}")

	w("")
	w("// Unmarshal decodes %s from protobuf wire format.", ct.Name)
	w("func (m *%s) Unmarshal(data []byte) (retErr error) {", ct.Name)
	w("\tdefer func() { if r := recover(); r != nil { retErr = fmt.Errorf(\"pb: decode %s: %%v\", r) } }()", ct.Name)
	w("\trd := pb.NewReader(data)")
	w("\tfor !rd.Done() {")
	w("\t\tfield, wire := rd.Tag()")
	w("\t\tswitch field {")
	for _, f := range ct.Fields {
		w("\t\tcase %d: m.%s = rd.%s()", f.ProtoTag, f.GoName, goWriterMethod[f.ProtoType])
	}
	w("\t\tdefault: rd.Skip(wire)")
	w("\t\t}")
	w("\t}")
	w("\treturn nil")
	w("}")
}

// writeGoCollectionMarshal emits the marshal code for a list or map field.
// optional=true skips encoding when the field is nil (used for delta fields).
func writeGoCollectionMarshal(b *strings.Builder, v schema.VarInfo, tag int, optional bool) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	if v.IsRepeated {
		if optional {
			w("\tif m.%s != nil {", v.GoName)
			w("\t\tif len(m.%s) == 0 {", v.GoName)
			w("\t\t\tw.Tag(%d, 2).Bytes(nil)", tag)
			w("\t\t} else {")
			w("\t\t\tfor _, _elem := range m.%s {", v.GoName)
			emitGoCollectionElemMarshal(b, v, tag, "\t\t\t\t")
			w("\t\t\t}")
			w("\t\t}")
			w("\t}")
		} else {
			w("\tfor _, _elem := range m.%s {", v.GoName)
			emitGoCollectionElemMarshal(b, v, tag, "\t\t")
			w("\t}")
		}
	} else { // IsMap
		if optional {
			w("\tif m.%s != nil {", v.GoName)
			w("\t\tif len(m.%s) == 0 {", v.GoName)
			w("\t\t\tw.Tag(%d, 2).Bytes(nil)", tag)
			w("\t\t} else {")
			w("\t\t\tfor _k, _v := range m.%s {", v.GoName)
			emitGoMapEntryMarshal(b, v, tag, "\t\t\t\t")
			w("\t\t\t}")
			w("\t\t}")
			w("\t}")
		} else {
			w("\tfor _k, _v := range m.%s {", v.GoName)
			emitGoMapEntryMarshal(b, v, tag, "\t\t")
			w("\t}")
		}
	}
}

// emitGoCollectionElemMarshal emits the single-element encode call for a list field.
func emitGoCollectionElemMarshal(b *strings.Builder, v schema.VarInfo, tag int, indent string) {
	if v.ElemIsCustom {
		fmt.Fprintf(b, indent+"w.Tag(%d, 2).Bytes(_elem.Marshal())\n", tag)
	} else {
		// Encode scalar in a sub-writer so all list elements use wire type 2 uniformly.
		fmt.Fprintf(b, "{ _inner := &pb.Writer{}; _inner.%s(_elem); w.Tag(%d, 2).Bytes(_inner.Finish()) }\n",
			goWriterMethod[v.ElemProtoType], tag)
	}
}

// emitGoMapEntryMarshal emits the K/V sub-message encode call for one map entry.
func emitGoMapEntryMarshal(b *strings.Builder, v schema.VarInfo, tag int, indent string) {
	w := func(f string, a ...any) { fmt.Fprintf(b, indent+f+"\n", a...) }
	keyWT := protoWireType[v.MapKeyProtoType]
	keyWM := goWriterMethod[v.MapKeyProtoType]
	w("_kv := &pb.Writer{}")
	w("_kv.Tag(1, %d).%s(_k)", keyWT, keyWM)
	if v.ElemIsCustom {
		w("_kv.Tag(2, 2).Bytes(_v.Marshal())")
	} else {
		valWT := protoWireType[v.ElemProtoType]
		valWM := goWriterMethod[v.ElemProtoType]
		w("_kv.Tag(2, %d).%s(_v)", valWT, valWM)
	}
	w("w.Tag(%d, 2).Bytes(_kv.Finish())", tag)
}

// writeGoCollectionUnmarshal emits the case + decode logic for a list or map field.
// optional=true initializes nil collections on first appearance (used for delta fields).
func writeGoCollectionUnmarshal(b *strings.Builder, v schema.VarInfo, tag int, optional bool) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }

	w("\t\tcase %d:", tag)
	if v.IsRepeated {
		if optional {
			w("\t\t\tif m.%s == nil { m.%s = %s{} }", v.GoName, v.GoName, v.GoType)
		}
		w("\t\t\t_b := rd.Bytes()")
		w("\t\t\tif len(_b) > 0 {")
		emitGoCollectionElemUnmarshal(b, v, "\t\t\t\t")
		w("\t\t\t}")
	} else { // IsMap
		w("\t\t\t_b := rd.Bytes()")
		w("\t\t\tif len(_b) > 0 {")
		emitGoMapEntryUnmarshal(b, v, "\t\t\t\t")
		w("\t\t\t} else {")
		w("\t\t\t\tif m.%s == nil { m.%s = %s{} }", v.GoName, v.GoName, v.GoType)
		w("\t\t\t}")
	}
}

// emitGoCollectionElemUnmarshal emits the decode + append for one list element.
func emitGoCollectionElemUnmarshal(b *strings.Builder, v schema.VarInfo, indent string) {
	w := func(f string, a ...any) { fmt.Fprintf(b, indent+f+"\n", a...) }
	if v.ElemIsCustom {
		w("var _elem %s", v.ElemProtoType)
		w("if _err := _elem.Unmarshal(_b); _err != nil { return _err }")
		w("m.%s = append(m.%s, _elem)", v.GoName, v.GoName)
	} else {
		w("_inner := pb.NewReader(_b)")
		w("m.%s = append(m.%s, _inner.%s())", v.GoName, v.GoName, goWriterMethod[v.ElemProtoType])
	}
}

// emitGoMapEntryUnmarshal emits the K/V sub-message decode + assignment for one map entry.
func emitGoMapEntryUnmarshal(b *strings.Builder, v schema.VarInfo, indent string) {
	w := func(f string, a ...any) { fmt.Fprintf(b, indent+f+"\n", a...) }
	w("_rd := pb.NewReader(_b)")
	w("var _k %s", v.MapKeyGoType)
	w("var _v %s", v.ElemGoType)
	w("for !_rd.Done() {")
	w("\t_f, _ := _rd.Tag()")
	w("\tswitch _f {")
	w("\tcase 1: _k = _rd.%s()", goWriterMethod[v.MapKeyProtoType])
	if v.ElemIsCustom {
		w("\tcase 2:")
		w("\t\tif _err := _v.Unmarshal(_rd.Bytes()); _err != nil { return _err }")
	} else {
		w("\tcase 2: _v = _rd.%s()", goWriterMethod[v.ElemProtoType])
	}
	w("\t}")
	w("}")
	w("if m.%s == nil { m.%s = %s{} }", v.GoName, v.GoName, v.GoType)
	w("m.%s[_k] = _v", v.GoName)
}

// writeGoFieldEncode emits a single field encode line for a required or optional field.
func writeGoFieldEncode(b *strings.Builder, goName, protoType string, tag int, optional bool) {
	w := func(f string, a ...any) { fmt.Fprintf(b, f+"\n", a...) }
	wt := protoWireType[protoType]
	wm := goWriterMethod[protoType]

	if optional {
		w("\tif m.%s != nil { w.Tag(%d, %d).%s(*m.%s) }", goName, tag, wt, wm, goName)
		return
	}

	switch protoType {
	case "bool":
		w("\tif m.%s { w.Tag(%d, %d).%s(m.%s) }", goName, tag, wt, wm, goName)
	case "bytes":
		w("\tif len(m.%s) > 0 { w.Tag(%d, %d).%s(m.%s) }", goName, tag, wt, wm, goName)
	default:
		zero := goZeroExpr[protoType]
		w("\tif m.%s != %s { w.Tag(%d, %d).%s(m.%s) }", goName, zero, tag, wt, wm, goName)
	}
}
