package codegen

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/demiurgos-hub/golem-engine/schema"
)

// TestGenerateGoSharedTemplateSnapshotHelpersBehavior builds a temporary module
// from shared.go.tmpl and runs behavior tests for LoadSnapshotIfExists and
// RunSnapshotAutosave against real golem.Server snapshot APIs.
func TestGenerateGoSharedTemplateSnapshotHelpersBehavior(t *testing.T) {
	tmpl, err := loadEmbeddedTemplate("templates/go_server/shared.go.tmpl")
	if err != nil {
		t.Fatalf("loadEmbeddedTemplate: %v", err)
	}

	data := schema.SharedData{
		GolemImport: "github.com/demiurgos-hub/golem-engine/golem",
		GoPackage:   "snapruntimetest",
		Fingerprint: "unit5-fingerprint",
		Entities:    []schema.EntityData{{Name: "Probe"}},
	}
	var generated bytes.Buffer
	if err := tmpl.Execute(&generated, data); err != nil {
		t.Fatalf("Execute: %v", err)
	}

	repoRoot, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	// codegen tests run with cwd = codegen/; repo root is the parent.
	repoRoot = filepath.Clean(filepath.Join(repoRoot, ".."))
	repoRootSlash := filepath.ToSlash(repoRoot)

	dir := t.TempDir()
	write := func(name, content string) {
		t.Helper()
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("WriteFile %s: %v", name, err)
		}
	}

	write("go.mod", strings.ReplaceAll(`module snapruntimetest

go 1.25.4

require github.com/demiurgos-hub/golem-engine v0.0.0

replace github.com/demiurgos-hub/golem-engine => REPO

replace github.com/demiurgos-hub/golem-engine/golem/collision => REPO/golem/collision

replace github.com/demiurgos-hub/golem-engine/golem/nav => REPO/golem/nav
`, "REPO", repoRootSlash))
	write("golem_helpers.go", generated.String())
	write("stubs.go", snapshotHelperStubs)
	write("helpers_test.go", snapshotHelperBehaviorTests)

	env := []string{"GOWORK=off"}
	for _, kv := range os.Environ() {
		if strings.HasPrefix(kv, "GOWORK=") {
			continue
		}
		env = append(env, kv)
	}
	tidy := exec.Command("go", "mod", "tidy")
	tidy.Dir = dir
	tidy.Env = env
	if out, err := tidy.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy in generated harness failed: %v\n%s", err, out)
	}
	cmd := exec.Command("go", "test", "-count=1", ".")
	cmd.Dir = dir
	cmd.Env = env
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go test in generated harness failed: %v\n%s", err, out)
	}
}

func TestGenerateGoClientTemplatesOmitSnapshotAutosaveHelpers(t *testing.T) {
	for _, path := range []string{
		"templates/go_client/manager.go.tmpl",
		"templates/go_client/create_client.go.tmpl",
	} {
		tmpl, err := loadEmbeddedTemplate(path)
		if err != nil {
			t.Fatalf("loadEmbeddedTemplate %s: %v", path, err)
		}
		var out bytes.Buffer
		if err := tmpl.Execute(&out, schema.SharedData{
			GolemImport: "github.com/demiurgos-hub/golem-engine/golem-go-client",
			GoPackage:   "client",
		}); err != nil {
			t.Fatalf("Execute %s: %v", path, err)
		}
		content := out.String()
		for _, ban := range []string{
			"LoadSnapshotIfExists",
			"RunSnapshotAutosave",
			"runSnapshotAutosave",
		} {
			if strings.Contains(content, ban) {
				t.Fatalf("%s unexpectedly contains %q", path, ban)
			}
		}
	}
}

const snapshotHelperStubs = `package snapruntimetest

import (
	"encoding/binary"

	"github.com/demiurgos-hub/golem-engine/golem"
)

// Minimal protobuf / SyncedProbe stubs so generated RestoreEntity can round-trip.

type EntityUpdate struct {
	Payload isEntityUpdate_Payload
}

type isEntityUpdate_Payload interface{ isEntityUpdate_Payload() }

type EntityRemoved struct {
	EntityId int64
	Revision uint64
}

type EntityUpdate_EntityRemoved struct {
	EntityRemoved *EntityRemoved
}

func (*EntityUpdate_EntityRemoved) isEntityUpdate_Payload() {}

type ProbeState struct {
	EntityId int64
	Token    byte
}

type EntityUpdate_ProbeState struct {
	ProbeState *ProbeState
}

func (*EntityUpdate_ProbeState) isEntityUpdate_Payload() {}

type SyncedProbe struct {
	id    int64
	token byte
	srv   *golem.Server
}

func (e *SyncedProbe) EntityID() int64              { return e.id }
func (e *SyncedProbe) SetEntityID(id int64)         { e.id = id }
func (e *SyncedProbe) TypeName() string             { return "Probe" }
func (e *SyncedProbe) Position() (float32, float32) { return 0, 0 }
func (e *SyncedProbe) IsGlobal() bool               { return false }
func (e *SyncedProbe) FlushUpdate() ([]byte, error) { return nil, nil }
func (e *SyncedProbe) BindServer(srv *golem.Server) { e.srv = srv }
func (e *SyncedProbe) Server() *golem.Server        { return e.srv }

func (e *SyncedProbe) FullUpdate() ([]byte, error) {
	buf := make([]byte, 10)
	buf[0] = 'P'
	binary.BigEndian.PutUint64(buf[1:9], uint64(e.id))
	buf[9] = e.token
	return buf, nil
}

func (e *SyncedProbe) ApplyState(st *ProbeState) {
	if st == nil {
		return
	}
	e.id = st.EntityId
	e.token = st.Token
}

func (m *EntityUpdate) Marshal() []byte { return nil }

func (m *EntityUpdate) Unmarshal(data []byte) error {
	if len(data) == 10 && data[0] == 'P' {
		m.Payload = &EntityUpdate_ProbeState{
			ProbeState: &ProbeState{
				EntityId: int64(binary.BigEndian.Uint64(data[1:9])),
				Token:    data[9],
			},
		}
	}
	return nil
}
`

const snapshotHelperBehaviorTests = `package snapruntimetest

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"sync/atomic"
	"testing"
	"time"

	"github.com/demiurgos-hub/golem-engine/golem"
	"github.com/demiurgos-hub/golem-engine/golem/snapshot"
)

func TestLoadSnapshotIfExistsAbsentFile(t *testing.T) {
	_, rt := NewServer(golem.ServerConfig{})
	path := filepath.Join(t.TempDir(), "missing.snap")
	ok, err := rt.LoadSnapshotIfExists(path)
	if err != nil {
		t.Fatalf("LoadSnapshotIfExists: %v", err)
	}
	if ok {
		t.Fatal("LoadSnapshotIfExists ok = true, want false for absent file")
	}
}

func TestLoadSnapshotIfExistsSuccessfulLoad(t *testing.T) {
	path := filepath.Join(t.TempDir(), "world.snap")
	if err := <-snapshot.Save(nil, SchemaFingerprint, path); err != nil {
		t.Fatalf("Save: %v", err)
	}
	_, rt := NewServer(golem.ServerConfig{})
	ok, err := rt.LoadSnapshotIfExists(path)
	if err != nil {
		t.Fatalf("LoadSnapshotIfExists: %v", err)
	}
	if !ok {
		t.Fatal("LoadSnapshotIfExists ok = false, want true")
	}
}

func TestLoadSnapshotIfExistsFingerprintMismatch(t *testing.T) {
	path := filepath.Join(t.TempDir(), "world.snap")
	if err := <-snapshot.Save(nil, "other-fingerprint", path); err != nil {
		t.Fatalf("Save: %v", err)
	}
	_, rt := NewServer(golem.ServerConfig{})
	ok, err := rt.LoadSnapshotIfExists(path)
	if ok {
		t.Fatal("LoadSnapshotIfExists ok = true, want false")
	}
	if !errors.Is(err, snapshot.ErrFingerprintMismatch) {
		t.Fatalf("error = %v, want errors.Is(..., snapshot.ErrFingerprintMismatch)", err)
	}
}

func TestLoadSnapshotIfExistsReadError(t *testing.T) {
	dir := t.TempDir()
	// ReadFile/Load on a directory is not ErrNotExist on any supported platform.
	_, rt := NewServer(golem.ServerConfig{})
	ok, err := rt.LoadSnapshotIfExists(dir)
	if ok {
		t.Fatal("LoadSnapshotIfExists ok = true, want false")
	}
	if err == nil {
		t.Fatal("LoadSnapshotIfExists err = nil, want read/stat error")
	}
	if errors.Is(err, os.ErrNotExist) {
		t.Fatalf("directory load must not collapse to ErrNotExist: %v", err)
	}
}

func TestRunSnapshotAutosaveInvalidIntervalBeforeSetup(t *testing.T) {
	for _, interval := range []time.Duration{0, -time.Second} {
		err := startSnapshotAutosave(context.Background(), interval, func() <-chan error {
			t.Fatal("save must not start for non-positive interval")
			return nil
		}, func(d time.Duration) *time.Ticker {
			t.Fatalf("ticker must not be created for non-positive interval (got %v)", d)
			return nil
		})
		if err == nil {
			t.Fatalf("startSnapshotAutosave(interval=%v) err = nil, want error", interval)
		}
	}
}

func TestRunSnapshotAutosaveNilContext(t *testing.T) {
	err := startSnapshotAutosave(nil, time.Second, func() <-chan error {
		t.Fatal("save must not start for nil context")
		return nil
	}, func(d time.Duration) *time.Ticker {
		t.Fatalf("ticker must not be created for nil context (got %v)", d)
		return nil
	})
	if err == nil {
		t.Fatal("startSnapshotAutosave(nil ctx) err = nil, want error")
	}
}

func TestRunSnapshotAutosaveCancelBeforeFirstTick(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	err := runSnapshotAutosave(ctx, make(chan time.Time), func() <-chan error {
		t.Fatal("save must not run when cancelled before first tick")
		return nil
	})
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("error = %v, want context.Canceled", err)
	}
}

func TestRunSnapshotAutosaveCancelPrefersOverBufferedTick(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	ticks := make(chan time.Time, 1)
	ticks <- time.Time{}
	err := runSnapshotAutosave(ctx, ticks, func() <-chan error {
		t.Fatal("save must not start when ctx already cancelled with a buffered tick")
		return nil
	})
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("error = %v, want context.Canceled", err)
	}
}

func TestRunSnapshotAutosaveSerializedSaves(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	ticks := make(chan time.Time)
	release := make(chan struct{})
	var started atomic.Int32
	var maxStarted atomic.Int32

	save := func() <-chan error {
		errc := make(chan error, 1)
		cur := started.Add(1)
		for {
			old := maxStarted.Load()
			if cur <= old || maxStarted.CompareAndSwap(old, cur) {
				break
			}
		}
		go func() {
			<-release
			started.Add(-1)
			errc <- nil
		}()
		return errc
	}

	done := make(chan error, 1)
	go func() { done <- runSnapshotAutosave(ctx, ticks, save) }()

	ticks <- time.Time{}
	secondTickAccepted := make(chan struct{})
	go func() {
		ticks <- time.Time{}
		close(secondTickAccepted)
	}()

	select {
	case <-secondTickAccepted:
		t.Fatal("second tick accepted while first save still in flight")
	default:
	}
	if got := started.Load(); got != 1 {
		t.Fatalf("in-flight saves = %d, want 1", got)
	}

	release <- struct{}{}
	<-secondTickAccepted
	release <- struct{}{}
	cancel()
	if err := <-done; !errors.Is(err, context.Canceled) {
		t.Fatalf("error = %v, want context.Canceled", err)
	}
	if got := maxStarted.Load(); got != 1 {
		t.Fatalf("max concurrent saves = %d, want 1", got)
	}
}

func TestRunSnapshotAutosaveSaveError(t *testing.T) {
	boom := errors.New("save failed")
	ticks := make(chan time.Time, 1)
	ticks <- time.Time{}
	err := runSnapshotAutosave(context.Background(), ticks, func() <-chan error {
		errc := make(chan error, 1)
		errc <- boom
		return errc
	})
	if !errors.Is(err, boom) {
		t.Fatalf("error = %v, want save failed", err)
	}
}

func TestRunSnapshotAutosaveCancelDuringInFlightSave(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	ticks := make(chan time.Time, 1)
	ticks <- time.Time{}
	started := make(chan struct{})
	release := make(chan struct{})

	done := make(chan error, 1)
	go func() {
		done <- runSnapshotAutosave(ctx, ticks, func() <-chan error {
			errc := make(chan error, 1)
			go func() {
				close(started)
				<-release
				errc <- nil
			}()
			return errc
		})
	}()

	<-started
	cancel()
	select {
	case err := <-done:
		t.Fatalf("returned before in-flight save finished: %v", err)
	default:
	}
	close(release)
	err := <-done
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("error = %v, want context.Canceled", err)
	}
}

func TestRunSnapshotAutosaveCancelDuringFailedInFlightSave(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	ticks := make(chan time.Time, 1)
	ticks <- time.Time{}
	started := make(chan struct{})
	release := make(chan struct{})
	boom := errors.New("save failed")

	done := make(chan error, 1)
	go func() {
		done <- runSnapshotAutosave(ctx, ticks, func() <-chan error {
			errc := make(chan error, 1)
			go func() {
				close(started)
				<-release
				errc <- boom
			}()
			return errc
		})
	}()

	<-started
	cancel()
	close(release)
	err := <-done
	if !errors.Is(err, boom) {
		t.Fatalf("error = %v, want save error to take precedence over cancel", err)
	}
}

func TestRunSnapshotAutosaveExportedCancelBeforeFirstTick(t *testing.T) {
	_, rt := NewServer(golem.ServerConfig{})
	path := filepath.Join(t.TempDir(), "auto.snap")
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	err := rt.RunSnapshotAutosave(ctx, path, time.Hour)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("RunSnapshotAutosave: %v, want context.Canceled", err)
	}
	if _, err := os.Stat(path); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("cancelled autosave must not create snapshot: %v", err)
	}
}

func TestRuntimeSaveSnapshotWritesFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "auto.snap")
	srv, rt := NewServer(golem.ServerConfig{})
	ent := &SyncedProbe{token: 0x7}
	if err := srv.CreateEntity(ent); err != nil {
		t.Fatalf("CreateEntity: %v", err)
	}
	if err := <-rt.SaveSnapshot(path); err != nil {
		t.Fatalf("SaveSnapshot: %v", err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("SaveSnapshot did not write file: %v", err)
	}
}

func TestRuntimeLoadSnapshotIfExistsRestoresGeneratedEntity(t *testing.T) {
	path := filepath.Join(t.TempDir(), "world.snap")
	src, rt := NewServer(golem.ServerConfig{})
	ent := &SyncedProbe{token: 0x42}
	if err := src.CreateEntity(ent); err != nil {
		t.Fatalf("CreateEntity: %v", err)
	}
	id := ent.EntityID()
	if id == 0 {
		t.Fatal("CreateEntity left EntityID=0")
	}
	if err := <-rt.SaveSnapshot(path); err != nil {
		t.Fatalf("SaveSnapshot: %v", err)
	}

	dst, rt2 := NewServer(golem.ServerConfig{})
	ok, err := rt2.LoadSnapshotIfExists(path)
	if err != nil || !ok {
		t.Fatalf("LoadSnapshotIfExists: ok=%v err=%v", ok, err)
	}
	got, found := dst.Get(id)
	if !found {
		t.Fatalf("restored entity id=%d missing (unknown-type skip would also fail here)", id)
	}
	probe, ok := got.(*SyncedProbe)
	if !ok {
		t.Fatalf("restored type = %T, want *SyncedProbe", got)
	}
	if probe.token != 0x42 {
		t.Fatalf("restored token = %#x, want 0x42", probe.token)
	}
}
`
