package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"golem-engine/schema"
)

// protoWireType maps protobuf scalar type names to their wire type numbers.
var protoWireType = map[string]int{
	"double": 1, // 64-bit
	"float":  5, // 32-bit
	"int32":  0, // varint
	"int64":  0,
	"uint32": 0,
	"uint64": 0,
	"sint32": 0,
	"sint64": 0,
	"bool":   0,
	"string": 2, // length-delimited
	"bytes":  2,
}

// protoReaderMethod maps protobuf types to the PbReader method name.
var protoReaderMethod = map[string]string{
	"double": "double",
	"float":  "float",
	"int32":  "int32",
	"int64":  "int64",
	"uint32": "uint32",
	"uint64": "uint64",
	"sint32": "sint32",
	"sint64": "sint64",
	"bool":   "bool",
	"string": "string",
	"bytes":  "bytes",
}

// protoWriterMethod mirrors protoReaderMethod for PbWriter.
var protoWriterMethod = map[string]string{
	"double": "double",
	"float":  "float",
	"int32":  "int32",
	"int64":  "int64",
	"uint32": "uint32",
	"uint64": "uint64",
	"sint32": "sint32",
	"sint64": "sint64",
	"bool":   "bool",
	"string": "string",
	"bytes":  "bytes",
}

// protoTSDefault returns the TypeScript zero value for a protobuf scalar type.
var protoTSDefault = map[string]string{
	"double": "0",
	"float":  "0",
	"int32":  "0",
	"int64":  "0",
	"uint32": "0",
	"uint64": "0",
	"sint32": "0",
	"sint64": "0",
	"bool":   "false",
	"string": `""`,
	"bytes":  "new Uint8Array()",
}

// protoTSZero returns the TypeScript equality check against zero for encode skipping.
var protoTSZero = map[string]string{
	"double": "0",
	"float":  "0",
	"int32":  "0",
	"int64":  "0",
	"uint32": "0",
	"uint64": "0",
	"sint32": "0",
	"sint64": "0",
	"bool":   "false",
	"string": `""`,
	"bytes":  "", // check .length
}

// generateJSProto writes entities_pb.ts into outDir with protobuf encode/decode
// classes for all entities, EntityUpdate, EntityRemoved, commands, and ClientMessage.
// When world types or events exist, it also writes world_pb.ts and events_pb.ts.
func generateJSProto(
	outDir string,
	golemImport string,
	entities []schema.EntityData,
	commands []schema.CommandData,
	worldTypes []schema.WorldTypeData,
	events []schema.EventData,
	proto schema.ProtoTemplateData,
) error {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("// GENERATED by Golem Engine — do not edit.")
	w("import { PbWriter, PbReader } from %q;\n", golemImport)

	for _, ct := range proto.CustomTypes {
		writeJSCustomTypeInterface(&b, ct)
	}

	// Per-entity State + Delta classes
	for _, ent := range entities {
		writeMessageClass(&b, ent.Name+"State", entityStateFields(ent), false)
		writeMessageClass(&b, ent.Name+"Delta", entityDeltaFields(ent), true)
	}

	// EntityRemoved
	writeMessageClass(&b, "EntityRemoved", []msgField{
		{Name: "entityId", ProtoType: "int64", Tag: 1},
		{Name: "revision", ProtoType: "uint64", Tag: entityRevisionProtoTag},
	}, false)

	// EntityUpdate (decode-only, oneof)
	writeEntityUpdateClass(&b, proto)

	// Command messages (encode-only)
	for _, cmd := range commands {
		writeCommandClass(&b, cmd)
	}

	// ClientMessage (encode-only, oneof wrapper)
	if len(commands) > 0 {
		writeClientMessageClass(&b, proto)
		writeClientPacketClass(&b)
	}

	outPath := filepath.Join(outDir, "entities_pb.ts")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  wrote %s\n", outPath)

	if len(worldTypes) > 0 {
		if err := generateJSWorldProto(outDir, golemImport, proto); err != nil {
			return err
		}
	}
	if len(events) > 0 {
		if err := generateJSEventProto(outDir, golemImport, proto); err != nil {
			return err
		}
	}
	return nil
}

type msgField struct {
	Name            string
	ProtoType       string
	Tag             int
	IsOptional      bool // true for scalar delta fields
	IsRepeated      bool
	IsMap           bool
	MapKeyProtoType string
	ElemProtoType   string
	ElemIsCustom    bool
	ElemTSType      string
	MapKeyTSType    string
}

func entityStateFields(ent schema.EntityData) []msgField {
	fields := []msgField{
		{Name: "entityId", ProtoType: "int64", Tag: 1},
		{Name: "posX", ProtoType: "float", Tag: 2},
		{Name: "posY", ProtoType: "float", Tag: 3},
	}
	if ent.Is3D {
		fields = append(fields, msgField{Name: "posZ", ProtoType: "float", Tag: 4})
	}
	fields = append(fields, msgField{Name: "revision", ProtoType: "uint64", Tag: entityRevisionProtoTag})
	for _, v := range ent.AllVars {
		fields = append(fields, varInfoToEntityMsgField(ent, v, false))
	}
	return fields
}

func entityDeltaFields(ent schema.EntityData) []msgField {
	fields := []msgField{
		{Name: "entityId", ProtoType: "int64", Tag: 1},
		{Name: "posX", ProtoType: "float", Tag: 2, IsOptional: true},
		{Name: "posY", ProtoType: "float", Tag: 3, IsOptional: true},
	}
	if ent.Is3D {
		fields = append(fields, msgField{Name: "posZ", ProtoType: "float", Tag: 4, IsOptional: true})
	}
	fields = append(fields, msgField{Name: "revision", ProtoType: "uint64", Tag: entityRevisionProtoTag})
	for _, v := range ent.TickVars {
		mf := varInfoToEntityMsgField(ent, v, true)
		fields = append(fields, mf)
	}
	return fields
}

// varInfoToMsgField converts a VarInfo into a msgField. isDelta=true marks
// all non-entityId fields as optional (scalars use pointer semantics,
// collections use undefined-as-absent semantics).
func varInfoToMsgField(v schema.VarInfo, isDelta bool) msgField {
	mf := msgField{
		Name:            v.TSProtoField,
		ProtoType:       v.ProtoType,
		Tag:             v.ProtoTag,
		IsRepeated:      v.IsRepeated,
		IsMap:           v.IsMap,
		MapKeyProtoType: v.MapKeyProtoType,
		ElemProtoType:   v.ElemProtoType,
		ElemIsCustom:    v.ElemIsCustom,
		ElemTSType:      v.ElemTSType,
		MapKeyTSType:    v.MapKeyTSType,
		IsOptional:      isDelta,
	}
	return mf
}

func varInfoToEntityMsgField(ent schema.EntityData, v schema.VarInfo, isDelta bool) msgField {
	mf := varInfoToMsgField(v, isDelta)
	mf.Tag = entityProtoTag(ent, v.UserTag)
	return mf
}

func tsType(protoType string) string {
	switch protoType {
	case "bool":
		return "boolean"
	case "string":
		return "string"
	case "bytes":
		return "Uint8Array"
	default:
		return "number"
	}
}

// writeMessageClass emits a TS class with static encode/decode.
// Collection and optional semantics are driven by per-field flags in msgField.
func writeMessageClass(b *strings.Builder, name string, fields []msgField, _ bool) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("export class %s {", name)
	for i, f := range fields {
		isEntityId := i == 0 && f.Name == "entityId"
		switch {
		case f.IsRepeated:
			if f.IsOptional {
				w("  %s?: %s[];", f.Name, f.ElemTSType)
			} else {
				w("  %s: %s[] = [];", f.Name, f.ElemTSType)
			}
		case f.IsMap:
			if f.IsOptional {
				w("  %s?: Record<%s, %s>;", f.Name, f.MapKeyTSType, f.ElemTSType)
			} else {
				w("  %s: Record<%s, %s> = {};", f.Name, f.MapKeyTSType, f.ElemTSType)
			}
		case f.IsOptional && !isEntityId:
			w("  %s?: %s;", f.Name, tsType(f.ProtoType))
		default:
			w("  %s: %s = %s;", f.Name, tsType(f.ProtoType), protoTSDefault[f.ProtoType])
		}
	}
	w("")

	// encode
	w("  static encode(m: %s): Uint8Array {", name)
	w("    const w = new PbWriter();")
	for i, f := range fields {
		isEntityId := i == 0 && f.Name == "entityId"
		switch {
		case f.IsRepeated:
			writeJSCollectionEncode(b, f)
		case f.IsMap:
			writeJSMapEncode(b, f)
		case f.IsOptional && !isEntityId:
			wt := protoWireType[f.ProtoType]
			wm := protoWriterMethod[f.ProtoType]
			w("    if (m.%s !== undefined) w.tag(%d, %d).%s(m.%s);", f.Name, f.Tag, wt, wm, f.Name)
		case f.ProtoType == "bytes":
			wt := protoWireType[f.ProtoType]
			wm := protoWriterMethod[f.ProtoType]
			w("    if (m.%s.length > 0) w.tag(%d, %d).%s(m.%s);", f.Name, f.Tag, wt, wm, f.Name)
		default:
			wt := protoWireType[f.ProtoType]
			wm := protoWriterMethod[f.ProtoType]
			zero := protoTSZero[f.ProtoType]
			w("    if (m.%s !== %s) w.tag(%d, %d).%s(m.%s);", f.Name, zero, f.Tag, wt, wm, f.Name)
		}
	}
	w("    return w.finish();")
	w("  }")
	w("")

	// decode
	w("  static decode(b: Uint8Array): %s {", name)
	w("    const r = new PbReader(b);")
	w("    const m = new %s();", name)
	w("    while (!r.done) {")
	w("      const t = r.tag();")
	w("      switch (t.field) {")
	for _, f := range fields {
		switch {
		case f.IsRepeated:
			writeJSCollectionDecode(b, f)
		case f.IsMap:
			writeJSMapDecode(b, f)
		default:
			rm := protoReaderMethod[f.ProtoType]
			w("        case %d: m.%s = r.%s(); break;", f.Tag, f.Name, rm)
		}
	}
	w("        default: r.skip(t.wire); break;")
	w("      }")
	w("    }")
	w("    return m;")
	w("  }")
	w("}\n")
}

// writeJSCustomTypeInterface emits a TS interface plus private encode/decode helpers
// for one custom type. These helpers are used by collection fields in entity classes.
func writeJSCustomTypeInterface(b *strings.Builder, ct schema.CustomTypeData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("export interface %s {", ct.Name)
	for _, f := range ct.Fields {
		w("  %s: %s;", f.FieldName, tsType(f.ProtoType))
	}
	w("}")
	w("")

	// encode helper
	w("function encode%s(m: %s): Uint8Array {", ct.Name, ct.Name)
	w("  const w = new PbWriter();")
	for _, f := range ct.Fields {
		wt := protoWireType[f.ProtoType]
		wm := protoWriterMethod[f.ProtoType]
		if f.ProtoType == "bytes" {
			w("  if (m.%s.length > 0) w.tag(%d, %d).%s(m.%s);", f.FieldName, f.ProtoTag, wt, wm, f.FieldName)
		} else {
			zero := protoTSZero[f.ProtoType]
			w("  if (m.%s !== %s) w.tag(%d, %d).%s(m.%s);", f.FieldName, zero, f.ProtoTag, wt, wm, f.FieldName)
		}
	}
	w("  return w.finish();")
	w("}")
	w("")

	// decode helper
	w("function decode%s(b: Uint8Array): %s {", ct.Name, ct.Name)
	w("  const r = new PbReader(b);")
	// Build default object literal
	defaults := make([]string, 0, len(ct.Fields))
	for _, f := range ct.Fields {
		defaults = append(defaults, fmt.Sprintf("%s: %s", f.FieldName, protoTSDefault[f.ProtoType]))
	}
	w("  const m: %s = { %s };", ct.Name, strings.Join(defaults, ", "))
	w("  while (!r.done) {")
	w("    const t = r.tag();")
	w("    switch (t.field) {")
	for _, f := range ct.Fields {
		rm := protoReaderMethod[f.ProtoType]
		w("      case %d: m.%s = r.%s(); break;", f.ProtoTag, f.FieldName, rm)
	}
	w("      default: r.skip(t.wire); break;")
	w("    }")
	w("  }")
	w("  return m;")
	w("}")
	w("")
}

// writeJSCollectionEncode emits the encode block for a repeated field in a TS class.
func writeJSCollectionEncode(b *strings.Builder, f msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	if f.IsOptional {
		w("    if (m.%s !== undefined) {", f.Name)
		w("      if (m.%s.length === 0) { w.tag(%d, 2).bytes(new Uint8Array()); }", f.Name, f.Tag)
		w("      else for (const _e of m.%s) {", f.Name)
		writeJSCollectionElemEncode(b, f, "        ")
		w("      }")
		w("    }")
	} else {
		w("    for (const _e of m.%s) {", f.Name)
		writeJSCollectionElemEncode(b, f, "      ")
		w("    }")
	}
}

func writeJSCollectionElemEncode(b *strings.Builder, f msgField, indent string) {
	if f.ElemIsCustom {
		fmt.Fprintf(b, indent+"w.tag(%d, 2).bytes(encode%s(_e));\n", f.Tag, f.ElemProtoType)
	} else {
		wt := protoWireType[f.ElemProtoType]
		wm := protoWriterMethod[f.ElemProtoType]
		if wt == 2 {
			// string or bytes: no sub-writer needed, length-delimited natively
			fmt.Fprintf(b, indent+"w.tag(%d, 2).%s(_e);\n", f.Tag, wm)
		} else {
			// numeric: encode scalar into a sub-writer so all elements use wire type 2
			fmt.Fprintf(b, indent+"{ const _inner = new PbWriter(); _inner.%s(_e); w.tag(%d, 2).bytes(_inner.finish()); }\n", wm, f.Tag)
		}
	}
}

// writeJSCollectionDecode emits the case block for decoding a repeated field.
func writeJSCollectionDecode(b *strings.Builder, f msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	w("        case %d: {", f.Tag)
	if f.IsOptional {
		w("          if (m.%s === undefined) m.%s = [];", f.Name, f.Name)
	}
	w("          const _b = r.bytes();")
	w("          if (_b.length > 0) {")
	if f.ElemIsCustom {
		w("            m.%s.push(decode%s(_b));", f.Name, f.ElemProtoType)
	} else {
		wt := protoWireType[f.ElemProtoType]
		rm := protoReaderMethod[f.ElemProtoType]
		if wt == 2 {
			w("            const _inner = new PbReader(_b); m.%s.push(_inner.%s());", f.Name, rm)
		} else {
			w("            const _inner = new PbReader(_b); m.%s.push(_inner.%s());", f.Name, rm)
		}
	}
	w("          }")
	w("          break;")
	w("        }")
}

// writeJSMapEncode emits the encode block for a map field in a TS class.
func writeJSMapEncode(b *strings.Builder, f msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	keyWT := protoWireType[f.MapKeyProtoType]
	keyWM := protoWriterMethod[f.MapKeyProtoType]
	if f.IsOptional {
		w("    if (m.%s !== undefined) {", f.Name)
		w("      const _entries = Object.entries(m.%s);", f.Name)
		w("      if (_entries.length === 0) { w.tag(%d, 2).bytes(new Uint8Array()); }", f.Tag)
		w("      else for (const [_k, _v] of _entries) {")
		w("        const _kv = new PbWriter();")
		w("        _kv.tag(1, %d).%s(_k as any);", keyWT, keyWM)
		writeJSMapValueEncode(b, f, "        ")
		w("        w.tag(%d, 2).bytes(_kv.finish());", f.Tag)
		w("      }")
		w("    }")
	} else {
		w("    for (const [_k, _v] of Object.entries(m.%s)) {", f.Name)
		w("      const _kv = new PbWriter();")
		w("      _kv.tag(1, %d).%s(_k as any);", keyWT, keyWM)
		writeJSMapValueEncode(b, f, "      ")
		w("      w.tag(%d, 2).bytes(_kv.finish());", f.Tag)
		w("    }")
	}
}

func writeJSMapValueEncode(b *strings.Builder, f msgField, indent string) {
	if f.ElemIsCustom {
		fmt.Fprintf(b, indent+"_kv.tag(2, 2).bytes(encode%s(_v as any));\n", f.ElemProtoType)
	} else {
		valWT := protoWireType[f.ElemProtoType]
		valWM := protoWriterMethod[f.ElemProtoType]
		fmt.Fprintf(b, indent+"_kv.tag(2, %d).%s(_v as any);\n", valWT, valWM)
	}
}

// writeJSMapDecode emits the case block for decoding a map field.
func writeJSMapDecode(b *strings.Builder, f msgField) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	keyRM := protoReaderMethod[f.MapKeyProtoType]
	w("        case %d: {", f.Tag)
	w("          const _b = r.bytes();")
	w("          if (_b.length > 0) {")
	w("            const _r = new PbReader(_b);")
	w("            let _k: %s = %s, _v: %s = %s;", f.MapKeyTSType, protoTSDefault[f.MapKeyProtoType], f.ElemTSType, jsCollectionValDefault(f))
	w("            while (!_r.done) {")
	w("              const _t = _r.tag();")
	w("              switch (_t.field) {")
	w("                case 1: _k = _r.%s(); break;", keyRM)
	if f.ElemIsCustom {
		w("                case 2: _v = decode%s(_r.bytes()); break;", f.ElemProtoType)
	} else {
		valRM := protoReaderMethod[f.ElemProtoType]
		w("                case 2: _v = _r.%s(); break;", valRM)
	}
	w("                default: _r.skip(_t.wire);")
	w("              }")
	w("            }")
	if f.IsOptional {
		w("            if (m.%s === undefined) m.%s = {};", f.Name, f.Name)
	}
	w("            (m.%s as any)[_k] = _v;", f.Name)
	w("          } else {")
	if f.IsOptional {
		w("            if (m.%s === undefined) m.%s = {};", f.Name, f.Name)
	}
	w("          }")
	w("          break;")
	w("        }")
}

// jsCollectionValDefault returns the TS zero value for a collection element type.
func jsCollectionValDefault(f msgField) string {
	if f.ElemIsCustom {
		return "{} as any"
	}
	return protoTSDefault[f.ElemProtoType]
}

// writeEntityUpdateClass emits a decode-only class for the EntityUpdate oneof.
func writeEntityUpdateClass(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("export class EntityUpdate {")
	for _, uf := range proto.EntityUpdateFields {
		fieldName := schema.SnakeToCamel(uf.SnakeName)
		w("  %s?: %s;", fieldName, uf.MessageType)
	}
	w("  entityRemoved?: EntityRemoved;")
	w("")

	w("  static decode(b: Uint8Array): EntityUpdate {")
	w("    const r = new PbReader(b);")
	w("    const m = new EntityUpdate();")
	w("    while (!r.done) {")
	w("      const t = r.tag();")
	w("      switch (t.field) {")
	for _, uf := range proto.EntityUpdateFields {
		fieldName := schema.SnakeToCamel(uf.SnakeName)
		w("        case %d: m.%s = %s.decode(r.bytes()); break;", uf.Tag, fieldName, uf.MessageType)
	}
	w("        case %d: m.entityRemoved = EntityRemoved.decode(r.bytes()); break;", proto.EntityRemovedTag)
	w("        default: r.skip(t.wire); break;")
	w("      }")
	w("    }")
	w("    return m;")
	w("  }")
	w("}\n")
}

// writeCommandClass emits an encode-only class for one command message.
func writeCommandClass(b *strings.Builder, cmd schema.CommandData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("export class %sCommand {", cmd.Name)
	if cmd.Target == "entity" {
		w("  entityId: number = 0;")
	}
	for _, f := range cmd.Fields {
		if f.IsCustom {
			w("  %s: %s = %s;", f.FieldName, f.TSType, f.TSDefault)
		} else {
			w("  %s: %s = %s;", f.FieldName, tsType(f.ProtoType), protoTSDefault[f.ProtoType])
		}
	}
	w("")

	w("  static encode(m: %sCommand): Uint8Array {", cmd.Name)
	w("    const w = new PbWriter();")
	if cmd.Target == "entity" {
		w("    if (m.entityId !== 0) w.tag(1, 0).int64(m.entityId);")
	}
	for _, f := range cmd.Fields {
		if f.IsCustom {
			// Reuse the private encodeXxx helper emitted by writeJSCustomTypeInterface.
			// Guard on byteLength > 0 for parity with scalar omit-zero behavior: a
			// zero-value custom struct encodes to an empty Uint8Array.
			w("    { const _b = encode%s(m.%s); if (_b.byteLength > 0) w.tag(%d, 2).bytes(_b); }", f.ProtoType, f.FieldName, f.ProtoTag)
		} else {
			wt := protoWireType[f.ProtoType]
			wm := protoWriterMethod[f.ProtoType]
			if f.ProtoType == "bytes" {
				w("    if (m.%s.length > 0) w.tag(%d, %d).%s(m.%s);", f.FieldName, f.ProtoTag, wt, wm, f.FieldName)
			} else {
				zero := protoTSZero[f.ProtoType]
				w("    if (m.%s !== %s) w.tag(%d, %d).%s(m.%s);", f.FieldName, zero, f.ProtoTag, wt, wm, f.FieldName)
			}
		}
	}
	w("    return w.finish();")
	w("  }")
	w("}\n")
}

// writeClientMessageClass emits an encode-only ClientMessage class wrapping commands.
func writeClientMessageClass(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("export class ClientMessage {")
	for _, cmf := range proto.ClientMessageFields {
		fieldName := schema.SnakeToCamel(cmf.SnakeName)
		w("  %s?: %s;", fieldName, cmf.MessageType)
	}
	w("")

	w("  static encode(m: ClientMessage): Uint8Array {")
	w("    const w = new PbWriter();")
	for _, cmf := range proto.ClientMessageFields {
		fieldName := schema.SnakeToCamel(cmf.SnakeName)
		w("    if (m.%s) w.tag(%d, 2).bytes(%s.encode(m.%s));",
			fieldName, cmf.Tag, cmf.MessageType, fieldName)
	}
	w("    return w.finish();")
	w("  }")
	w("}\n")
}

// writeClientPacketClass emits an encode-only transport envelope for batches of
// already-encoded ClientMessage blobs.
func writeClientPacketClass(b *strings.Builder) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("export class ClientPacket {")
	w("  static encode(frames: Uint8Array[]): Uint8Array {")
	w("    const w = new PbWriter();")
	w("    for (const frame of frames) w.tag(1, 2).bytes(frame);")
	w("    return w.finish();")
	w("  }")
	w("}\n")
}

// --- World data classes (JS/TS) ---

// generateJSWorldProto writes world_pb.ts with per-world-type classes and
// a decode-only WorldUpdate class.
func generateJSWorldProto(outDir, golemImport string, proto schema.ProtoTemplateData) error {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("// GENERATED by Golem Engine — do not edit.")
	w("import { PbWriter, PbReader } from %q;\n", golemImport)

	for _, ct := range proto.CustomTypes {
		writeJSCustomTypeInterface(&b, ct)
	}

	for _, wt := range proto.WorldTypes {
		writeWorldDataClass(&b, wt)
	}

	writeWorldUpdateClass(&b, proto)

	outPath := filepath.Join(outDir, "world_pb.ts")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  wrote %s\n", outPath)
	return nil
}

// writeWorldDataClass emits a TS class with encode and decode for one world data type.
func writeWorldDataClass(b *strings.Builder, wt schema.WorldTypeData) {
	writeMessageClass(b, wt.DataName, worldDataFields(wt), false)
}

func worldDataFields(wt schema.WorldTypeData) []msgField {
	var fields []msgField
	for _, f := range wt.Fields {
		fields = append(fields, worldFieldToMsgField(f))
	}
	return fields
}

// worldFieldToMsgField converts a WorldFieldInfo into a msgField, including
// collection metadata so writeMessageClass handles lists and maps correctly.
func worldFieldToMsgField(f schema.WorldFieldInfo) msgField {
	return msgField{
		Name:            f.TSProtoField,
		ProtoType:       f.ProtoType,
		Tag:             f.ProtoTag,
		IsRepeated:      f.IsRepeated,
		IsMap:           f.IsMap,
		MapKeyProtoType: f.MapKeyProtoType,
		ElemProtoType:   f.ElemProtoType,
		ElemIsCustom:    f.ElemIsCustom,
		ElemTSType:      f.ElemTSType,
		MapKeyTSType:    f.MapKeyTSType,
	}
}

// writeWorldUpdateClass emits a decode-only WorldUpdate class (same pattern as EntityUpdate).
func writeWorldUpdateClass(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("export class WorldUpdate {")
	for _, wuf := range proto.WorldUpdateFields {
		fieldName := schema.SnakeToCamel(wuf.SnakeName)
		w("  %s?: %s;", fieldName, wuf.MessageType)
	}
	w("")

	w("  static decode(b: Uint8Array): WorldUpdate {")
	w("    const r = new PbReader(b);")
	w("    const m = new WorldUpdate();")
	w("    while (!r.done) {")
	w("      const t = r.tag();")
	w("      switch (t.field) {")
	for _, wuf := range proto.WorldUpdateFields {
		fieldName := schema.SnakeToCamel(wuf.SnakeName)
		w("        case %d: m.%s = %s.decode(r.bytes()); break;", wuf.Tag, fieldName, wuf.MessageType)
	}
	w("        default: r.skip(t.wire); break;")
	w("      }")
	w("    }")
	w("    return m;")
	w("  }")
	w("}\n")
}

// generateJSEventProto writes events_pb.ts with per-event classes and a
// decode-only ServerEvent wrapper for server-to-client events.
func generateJSEventProto(outDir, golemImport string, proto schema.ProtoTemplateData) error {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("// GENERATED by Golem Engine — do not edit.")
	w("import { PbWriter, PbReader } from %q;\n", golemImport)

	for _, ct := range proto.CustomTypes {
		writeJSCustomTypeInterface(&b, ct)
	}
	for _, ev := range proto.Events {
		writeJSEventClass(&b, ev)
	}
	writeServerEventClass(&b, proto)

	outPath := filepath.Join(outDir, "events_pb.ts")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("  wrote %s\n", outPath)
	return nil
}

// writeJSEventClass emits an event class with static encode/decode helpers.
func writeJSEventClass(b *strings.Builder, ev schema.EventData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("export class %sEvent {", ev.Name)
	if ev.EntityType != "" {
		w("  entityId: number = 0;")
	}
	for _, f := range ev.Fields {
		if f.IsCustom {
			w("  %s: %s = %s;", f.FieldName, f.TSType, f.TSDefault)
		} else {
			w("  %s: %s = %s;", f.FieldName, tsType(f.ProtoType), protoTSDefault[f.ProtoType])
		}
	}
	w("")

	w("  static encode(m: %sEvent): Uint8Array {", ev.Name)
	w("    const w = new PbWriter();")
	if ev.EntityType != "" {
		w("    if (m.entityId !== 0) w.tag(1, 0).int64(m.entityId);")
	}
	for _, f := range ev.Fields {
		if f.IsCustom {
			w("    { const _b = encode%s(m.%s); if (_b.byteLength > 0) w.tag(%d, 2).bytes(_b); }", f.ProtoType, f.FieldName, f.ProtoTag)
		} else {
			wt := protoWireType[f.ProtoType]
			wm := protoWriterMethod[f.ProtoType]
			if f.ProtoType == "bytes" {
				w("    if (m.%s.length > 0) w.tag(%d, %d).%s(m.%s);", f.FieldName, f.ProtoTag, wt, wm, f.FieldName)
			} else {
				zero := protoTSZero[f.ProtoType]
				w("    if (m.%s !== %s) w.tag(%d, %d).%s(m.%s);", f.FieldName, zero, f.ProtoTag, wt, wm, f.FieldName)
			}
		}
	}
	w("    return w.finish();")
	w("  }")
	w("")

	w("  static decode(b: Uint8Array): %sEvent {", ev.Name)
	w("    const r = new PbReader(b);")
	w("    const m = new %sEvent();", ev.Name)
	w("    while (!r.done) {")
	w("      const t = r.tag();")
	w("      switch (t.field) {")
	if ev.EntityType != "" {
		w("        case 1: m.entityId = r.int64(); break;")
	}
	for _, f := range ev.Fields {
		if f.IsCustom {
			w("        case %d: m.%s = decode%s(r.bytes()); break;", f.ProtoTag, f.FieldName, f.ProtoType)
		} else {
			rm := protoReaderMethod[f.ProtoType]
			w("        case %d: m.%s = r.%s(); break;", f.ProtoTag, f.FieldName, rm)
		}
	}
	w("        default: r.skip(t.wire); break;")
	w("      }")
	w("    }")
	w("    return m;")
	w("  }")
	w("}\n")
}

// writeServerEventClass emits a decode-only oneof wrapper for server events.
func writeServerEventClass(b *strings.Builder, proto schema.ProtoTemplateData) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	w("export class ServerEvent {")
	for _, sef := range proto.ServerEventFields {
		fieldName := schema.SnakeToCamel(sef.SnakeName)
		w("  %s?: %s;", fieldName, sef.MessageType)
	}
	w("")

	w("  static decode(b: Uint8Array): ServerEvent {")
	w("    const r = new PbReader(b);")
	w("    const m = new ServerEvent();")
	w("    while (!r.done) {")
	w("      const t = r.tag();")
	w("      switch (t.field) {")
	for _, sef := range proto.ServerEventFields {
		fieldName := schema.SnakeToCamel(sef.SnakeName)
		w("        case %d: m.%s = %s.decode(r.bytes()); break;", sef.Tag, fieldName, sef.MessageType)
	}
	w("        default: r.skip(t.wire); break;")
	w("      }")
	w("    }")
	w("    return m;")
	w("  }")
	w("}\n")
}
