package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/demiurgos-hub/golem-engine/schema"
)

// RemoveIntegration removes generated files for a configured shared-only bridge.
// It leaves configuration and hand-authored files intact. Remove the integration
// from golem.yaml afterwards to prevent the next bake from recreating the bridge.
func RemoveIntegration(projectRoot, name string) error {
	cfg, err := schema.LoadConfig(projectRoot)
	if err != nil {
		return err
	}
	config, ok := cfg.Integrations[name]
	if !ok {
		return fmt.Errorf("integration %q is not configured", name)
	}
	integration, err := GetIntegration(name)
	if err != nil {
		return err
	}
	if integration.Template != "" || integration.GenerateExtra != nil || integration.Finalize != nil || len(integration.SharedTemplates) == 0 {
		return fmt.Errorf("integration %q is not a shared-only bridge; automatic removal is unsupported", name)
	}
	root, err := filepath.EvalSymlinks(projectRoot)
	if err != nil {
		return err
	}
	root, err = filepath.Abs(root)
	if err != nil {
		return err
	}
	out := config.Out
	if !filepath.IsAbs(out) {
		out = filepath.Join(root, out)
	}
	out, err = filepath.EvalSymlinks(out)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	rel, err := filepath.Rel(root, out)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || filepath.IsAbs(rel) {
		return fmt.Errorf("integration output must stay inside the project")
	}
	var files []string
	for _, entry := range integration.SharedTemplates {
		if filepath.Base(entry.File) != entry.File {
			return fmt.Errorf("unsupported nested integration output %q", entry.File)
		}
		file := filepath.Join(out, entry.File)
		info, err := os.Lstat(file)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("refusing non-regular generated file %s", file)
		}
		bytes, err := os.ReadFile(file)
		if err != nil {
			return err
		}
		if !strings.HasPrefix(string(bytes), "// GENERATED by Golem Engine") {
			return fmt.Errorf("refusing file without Golem generated header: %s", file)
		}
		files = append(files, file)
	}
	for _, file := range files {
		if err := os.Remove(file); err != nil {
			return err
		}
		fmt.Printf("  removed %s\n", file)
	}
	return nil
}
