package codegen

import (
	"os"
	"path/filepath"
	"testing"
)

func TestRemoveIntegrationKeepsAuthoredFiles(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "golem.yaml"), []byte("integrations:\n  phaser:\n    out: bridges\n"), 0600); err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(root, "bridges")
	if err := os.Mkdir(out, 0700); err != nil {
		t.Fatal(err)
	}
	generated := filepath.Join(out, "GolemPhaser.ts")
	if err := os.WriteFile(generated, []byte("// GENERATED by Golem Engine — do not edit.\n"), 0600); err != nil {
		t.Fatal(err)
	}
	authored := filepath.Join(out, "my-view.ts")
	if err := os.WriteFile(authored, []byte("export const view = 1;"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := RemoveIntegration(root, "phaser"); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(generated); !os.IsNotExist(err) {
		t.Fatalf("generated bridge remains: %v", err)
	}
	if _, err := os.Stat(authored); err != nil {
		t.Fatal(err)
	}
	if err := RemoveIntegration(root, "phaser"); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(generated, []byte("// user source"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := RemoveIntegration(root, "phaser"); err == nil {
		t.Fatal("removed an unmarked file")
	}
}

func TestRemoveIntegrationRejectsOutputEscape(t *testing.T) {
	parent := t.TempDir()
	root := filepath.Join(parent, "project")
	if err := os.Mkdir(root, 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "golem.yaml"), []byte("integrations:\n  phaser:\n    out: ..\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := RemoveIntegration(root, "phaser"); err == nil {
		t.Fatal("accepted output outside project")
	}
}
