package codegen

import (
	"os"
	"path/filepath"
	"testing"
)

func TestRemoveThrelteIntegrationPreservesAuthoredComponents(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "golem.yaml"), []byte("integrations:\n  threlte:\n    out: bridge\n"), 0600); err != nil {
		t.Fatal(err)
	}
	out := filepath.Join(root, "bridge")
	if err := os.Mkdir(out, 0700); err != nil {
		t.Fatal(err)
	}
	bridge := filepath.Join(out, "GolemThrelte.ts")
	component := filepath.Join(out, "Actor.svelte")
	for path, body := range map[string]string{
		bridge:    "// GENERATED by Golem Engine — do not edit.\n",
		component: "<script>const mesh = 'authored';</script>\n",
	} {
		if err := os.WriteFile(path, []byte(body), 0600); err != nil {
			t.Fatal(err)
		}
	}
	if err := RemoveIntegration(root, "threlte"); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(bridge); !os.IsNotExist(err) {
		t.Fatalf("generated bridge remains: %v", err)
	}
	if _, err := os.Stat(component); err != nil {
		t.Fatal(err)
	}
	if err := RemoveIntegration(root, "threlte"); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(bridge, []byte("// authored"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := RemoveIntegration(root, "threlte"); err == nil {
		t.Fatal("removed authored bridge")
	}
}
