namespace GolemEngine.Unity.Editor
{
    /// <summary>Shared constants for Golem Scribe generated artifacts.</summary>
    public static class GolemScribeConstants
    {
        public const string MarkerLine = "# Generated by Golem Scribe. Do not edit.";
        public const string ManifestFileName = "scribe.golem.yaml";
        public const string ArtifactKindEntitySchema = "entity_schema";
        public const int ManifestVersion = 1;
        public const int ReservedRevisionProtoField = 1000;
    }
}
